//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/Align.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsAlign")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsAlign
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsAlign 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsAlign 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsAlign

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMapsforgeCoreGraphicsAlign_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsAlign || defined(INCLUDE_OrgMapsforgeCoreGraphicsAlign))
#define OrgMapsforgeCoreGraphicsAlign_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;
@class NSString;

typedef NS_ENUM(jint, OrgMapsforgeCoreGraphicsAlign_Enum) {
  OrgMapsforgeCoreGraphicsAlign_Enum_CENTER NS_SWIFT_NAME(center) = 0,
  OrgMapsforgeCoreGraphicsAlign_Enum_LEFT NS_SWIFT_NAME(left) = 1,
  OrgMapsforgeCoreGraphicsAlign_Enum_RIGHT NS_SWIFT_NAME(right) = 2,
};

#if J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION
#define OrgMapsforgeCoreGraphicsAlign_ORDINAL jint
#else
#define OrgMapsforgeCoreGraphicsAlign_ORDINAL OrgMapsforgeCoreGraphicsAlign_Enum
#endif


@interface OrgMapsforgeCoreGraphicsAlign : JavaLangEnum

#pragma mark Public

- (OrgMapsforgeCoreGraphicsAlign *)fromStringWithNSString:(NSString *)value;

+ (OrgMapsforgeCoreGraphicsAlign *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (OrgMapsforgeCoreGraphicsAlign_Enum)toNSEnum;

@property(readonly) OrgMapsforgeCoreGraphicsAlign_Enum enumValue;
+ (OrgMapsforgeCoreGraphicsAlign *)fromNSEnum:(OrgMapsforgeCoreGraphicsAlign_Enum)value;

- (OrgMapsforgeCoreGraphicsAlign_ORDINAL)ordinal NS_SWIFT_UNAVAILABLE("Use .enumValue");

- (nullable instancetype)initWithAlign:(OrgMapsforgeCoreGraphicsAlign_Enum)value;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreGraphicsAlign)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsAlign *OrgMapsforgeCoreGraphicsAlign_values_[];

inline OrgMapsforgeCoreGraphicsAlign *OrgMapsforgeCoreGraphicsAlign_get_CENTER(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsAlign, CENTER)

inline OrgMapsforgeCoreGraphicsAlign *OrgMapsforgeCoreGraphicsAlign_get_LEFT(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsAlign, LEFT)

inline OrgMapsforgeCoreGraphicsAlign *OrgMapsforgeCoreGraphicsAlign_get_RIGHT(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsAlign, RIGHT)

FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeCoreGraphicsAlign_values(void);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsAlign *OrgMapsforgeCoreGraphicsAlign_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsAlign *OrgMapsforgeCoreGraphicsAlign_fromOrdinal(OrgMapsforgeCoreGraphicsAlign_ORDINAL ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsAlign)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsAlign")
