//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/BaseBitmap.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsBaseBitmap")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsBaseBitmap
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsBaseBitmap 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsBaseBitmap 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsBaseBitmap

#if !defined (OrgMapsforgeCoreGraphicsBaseBitmap_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsBaseBitmap || defined(INCLUDE_OrgMapsforgeCoreGraphicsBaseBitmap))
#define OrgMapsforgeCoreGraphicsBaseBitmap_

#define RESTRICT_OrgMapsforgeCoreGraphicsBitmap 1
#define INCLUDE_OrgMapsforgeCoreGraphicsBitmap 1
#include "org/mapsforge/core/graphics/Bitmap.h"

@interface OrgMapsforgeCoreGraphicsBaseBitmap : NSObject < OrgMapsforgeCoreGraphicsBitmap > {
 @public
  id mutex_;
}

#pragma mark Public

- (instancetype)init;

- (id)getMutex;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreGraphicsBaseBitmap)

J2OBJC_FIELD_SETTER(OrgMapsforgeCoreGraphicsBaseBitmap, mutex_, id)

FOUNDATION_EXPORT void OrgMapsforgeCoreGraphicsBaseBitmap_init(OrgMapsforgeCoreGraphicsBaseBitmap *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsBaseBitmap)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsBaseBitmap")
