//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/Cap.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsCap")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsCap
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsCap 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsCap 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsCap

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMapsforgeCoreGraphicsCap_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsCap || defined(INCLUDE_OrgMapsforgeCoreGraphicsCap))
#define OrgMapsforgeCoreGraphicsCap_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;
@class NSString;

typedef NS_ENUM(jint, OrgMapsforgeCoreGraphicsCap_Enum) {
  OrgMapsforgeCoreGraphicsCap_Enum_BUTT NS_SWIFT_NAME(butt) = 0,
  OrgMapsforgeCoreGraphicsCap_Enum_ROUND NS_SWIFT_NAME(round) = 1,
  OrgMapsforgeCoreGraphicsCap_Enum_SQUARE NS_SWIFT_NAME(square) = 2,
};

#if J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION
#define OrgMapsforgeCoreGraphicsCap_ORDINAL jint
#else
#define OrgMapsforgeCoreGraphicsCap_ORDINAL OrgMapsforgeCoreGraphicsCap_Enum
#endif


@interface OrgMapsforgeCoreGraphicsCap : JavaLangEnum

#pragma mark Public

+ (OrgMapsforgeCoreGraphicsCap *)fromStringWithNSString:(NSString *)value;

+ (OrgMapsforgeCoreGraphicsCap *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (OrgMapsforgeCoreGraphicsCap_Enum)toNSEnum;

@property(readonly) OrgMapsforgeCoreGraphicsCap_Enum enumValue;
+ (OrgMapsforgeCoreGraphicsCap *)fromNSEnum:(OrgMapsforgeCoreGraphicsCap_Enum)value;

- (OrgMapsforgeCoreGraphicsCap_ORDINAL)ordinal NS_SWIFT_UNAVAILABLE("Use .enumValue");

- (nullable instancetype)initWithCap:(OrgMapsforgeCoreGraphicsCap_Enum)value;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreGraphicsCap)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsCap *OrgMapsforgeCoreGraphicsCap_values_[];

inline OrgMapsforgeCoreGraphicsCap *OrgMapsforgeCoreGraphicsCap_get_BUTT(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsCap, BUTT)

inline OrgMapsforgeCoreGraphicsCap *OrgMapsforgeCoreGraphicsCap_get_ROUND(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsCap, ROUND)

inline OrgMapsforgeCoreGraphicsCap *OrgMapsforgeCoreGraphicsCap_get_SQUARE(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsCap, SQUARE)

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsCap *OrgMapsforgeCoreGraphicsCap_fromStringWithNSString_(NSString *value);

FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeCoreGraphicsCap_values(void);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsCap *OrgMapsforgeCoreGraphicsCap_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsCap *OrgMapsforgeCoreGraphicsCap_fromOrdinal(OrgMapsforgeCoreGraphicsCap_ORDINAL ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsCap)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsCap")
