//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/Color.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsColor")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsColor
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsColor 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsColor 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsColor

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMapsforgeCoreGraphicsColor_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsColor || defined(INCLUDE_OrgMapsforgeCoreGraphicsColor))
#define OrgMapsforgeCoreGraphicsColor_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;
@class NSString;

typedef NS_ENUM(jint, OrgMapsforgeCoreGraphicsColor_Enum) {
  OrgMapsforgeCoreGraphicsColor_Enum_BLACK NS_SWIFT_NAME(black) = 0,
  OrgMapsforgeCoreGraphicsColor_Enum_BLUE NS_SWIFT_NAME(blue) = 1,
  OrgMapsforgeCoreGraphicsColor_Enum_GREEN NS_SWIFT_NAME(green) = 2,
  OrgMapsforgeCoreGraphicsColor_Enum_RED NS_SWIFT_NAME(red) = 3,
  OrgMapsforgeCoreGraphicsColor_Enum_TRANSPARENT NS_SWIFT_NAME(transparent) = 4,
  OrgMapsforgeCoreGraphicsColor_Enum_WHITE NS_SWIFT_NAME(white) = 5,
};

#if J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION
#define OrgMapsforgeCoreGraphicsColor_ORDINAL jint
#else
#define OrgMapsforgeCoreGraphicsColor_ORDINAL OrgMapsforgeCoreGraphicsColor_Enum
#endif


@interface OrgMapsforgeCoreGraphicsColor : JavaLangEnum

#pragma mark Public

+ (OrgMapsforgeCoreGraphicsColor *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (OrgMapsforgeCoreGraphicsColor_Enum)toNSEnum;

@property(readonly) OrgMapsforgeCoreGraphicsColor_Enum enumValue;
+ (OrgMapsforgeCoreGraphicsColor *)fromNSEnum:(OrgMapsforgeCoreGraphicsColor_Enum)value;

- (OrgMapsforgeCoreGraphicsColor_ORDINAL)ordinal NS_SWIFT_UNAVAILABLE("Use .enumValue");

- (nullable instancetype)initWithColor:(OrgMapsforgeCoreGraphicsColor_Enum)value;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreGraphicsColor)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsColor *OrgMapsforgeCoreGraphicsColor_values_[];

inline OrgMapsforgeCoreGraphicsColor *OrgMapsforgeCoreGraphicsColor_get_BLACK(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsColor, BLACK)

inline OrgMapsforgeCoreGraphicsColor *OrgMapsforgeCoreGraphicsColor_get_BLUE(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsColor, BLUE)

inline OrgMapsforgeCoreGraphicsColor *OrgMapsforgeCoreGraphicsColor_get_GREEN(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsColor, GREEN)

inline OrgMapsforgeCoreGraphicsColor *OrgMapsforgeCoreGraphicsColor_get_RED(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsColor, RED)

inline OrgMapsforgeCoreGraphicsColor *OrgMapsforgeCoreGraphicsColor_get_TRANSPARENT(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsColor, TRANSPARENT)

inline OrgMapsforgeCoreGraphicsColor *OrgMapsforgeCoreGraphicsColor_get_WHITE(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsColor, WHITE)

FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeCoreGraphicsColor_values(void);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsColor *OrgMapsforgeCoreGraphicsColor_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsColor *OrgMapsforgeCoreGraphicsColor_fromOrdinal(OrgMapsforgeCoreGraphicsColor_ORDINAL ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsColor)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsColor")
