//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/util/Constants.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreUtilConstants")
#ifdef RESTRICT_OrgMapsforgeCoreUtilConstants
#define INCLUDE_ALL_OrgMapsforgeCoreUtilConstants 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreUtilConstants 1
#endif
#undef RESTRICT_OrgMapsforgeCoreUtilConstants

#if !defined (OrgMapsforgeCoreUtilConstants_) && (INCLUDE_ALL_OrgMapsforgeCoreUtilConstants || defined(INCLUDE_OrgMapsforgeCoreUtilConstants))
#define OrgMapsforgeCoreUtilConstants_

@class JavaLangLong;

@interface OrgMapsforgeCoreUtilConstants : NSObject

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreUtilConstants)

inline jlong OrgMapsforgeCoreUtilConstants_get_MAX_MEMORY_MB(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jlong OrgMapsforgeCoreUtilConstants_MAX_MEMORY_MB;
J2OBJC_STATIC_FIELD_PRIMITIVE_FINAL(OrgMapsforgeCoreUtilConstants, MAX_MEMORY_MB, jlong)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreUtilConstants)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreUtilConstants")
