//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/Display.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsDisplay")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsDisplay
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsDisplay 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsDisplay 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsDisplay

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMapsforgeCoreGraphicsDisplay_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsDisplay || defined(INCLUDE_OrgMapsforgeCoreGraphicsDisplay))
#define OrgMapsforgeCoreGraphicsDisplay_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;
@class NSString;

typedef NS_ENUM(jint, OrgMapsforgeCoreGraphicsDisplay_Enum) {
  OrgMapsforgeCoreGraphicsDisplay_Enum_NEVER NS_SWIFT_NAME(never) = 0,
  OrgMapsforgeCoreGraphicsDisplay_Enum_ALWAYS NS_SWIFT_NAME(always) = 1,
  OrgMapsforgeCoreGraphicsDisplay_Enum_IFSPACE NS_SWIFT_NAME(ifspace) = 2,
};

#if J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION
#define OrgMapsforgeCoreGraphicsDisplay_ORDINAL jint
#else
#define OrgMapsforgeCoreGraphicsDisplay_ORDINAL OrgMapsforgeCoreGraphicsDisplay_Enum
#endif


@interface OrgMapsforgeCoreGraphicsDisplay : JavaLangEnum

#pragma mark Public

+ (OrgMapsforgeCoreGraphicsDisplay *)fromStringWithNSString:(NSString *)value;

+ (OrgMapsforgeCoreGraphicsDisplay *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (OrgMapsforgeCoreGraphicsDisplay_Enum)toNSEnum;

@property(readonly) OrgMapsforgeCoreGraphicsDisplay_Enum enumValue;
+ (OrgMapsforgeCoreGraphicsDisplay *)fromNSEnum:(OrgMapsforgeCoreGraphicsDisplay_Enum)value;

- (OrgMapsforgeCoreGraphicsDisplay_ORDINAL)ordinal NS_SWIFT_UNAVAILABLE("Use .enumValue");

- (nullable instancetype)initWithDisplay:(OrgMapsforgeCoreGraphicsDisplay_Enum)value;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreGraphicsDisplay)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsDisplay *OrgMapsforgeCoreGraphicsDisplay_values_[];

inline OrgMapsforgeCoreGraphicsDisplay *OrgMapsforgeCoreGraphicsDisplay_get_NEVER(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsDisplay, NEVER)

inline OrgMapsforgeCoreGraphicsDisplay *OrgMapsforgeCoreGraphicsDisplay_get_ALWAYS(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsDisplay, ALWAYS)

inline OrgMapsforgeCoreGraphicsDisplay *OrgMapsforgeCoreGraphicsDisplay_get_IFSPACE(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsDisplay, IFSPACE)

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsDisplay *OrgMapsforgeCoreGraphicsDisplay_fromStringWithNSString_(NSString *value);

FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeCoreGraphicsDisplay_values(void);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsDisplay *OrgMapsforgeCoreGraphicsDisplay_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsDisplay *OrgMapsforgeCoreGraphicsDisplay_fromOrdinal(OrgMapsforgeCoreGraphicsDisplay_ORDINAL ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsDisplay)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsDisplay")
