//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/FontStyle.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsFontStyle")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsFontStyle
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsFontStyle 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsFontStyle 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsFontStyle

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMapsforgeCoreGraphicsFontStyle_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsFontStyle || defined(INCLUDE_OrgMapsforgeCoreGraphicsFontStyle))
#define OrgMapsforgeCoreGraphicsFontStyle_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;
@class NSString;

typedef NS_ENUM(jint, OrgMapsforgeCoreGraphicsFontStyle_Enum) {
  OrgMapsforgeCoreGraphicsFontStyle_Enum_BOLD NS_SWIFT_NAME(bold) = 0,
  OrgMapsforgeCoreGraphicsFontStyle_Enum_BOLD_ITALIC NS_SWIFT_NAME(boldItalic) = 1,
  OrgMapsforgeCoreGraphicsFontStyle_Enum_ITALIC NS_SWIFT_NAME(italic) = 2,
  OrgMapsforgeCoreGraphicsFontStyle_Enum_NORMAL NS_SWIFT_NAME(normal) = 3,
};

#if J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION
#define OrgMapsforgeCoreGraphicsFontStyle_ORDINAL jint
#else
#define OrgMapsforgeCoreGraphicsFontStyle_ORDINAL OrgMapsforgeCoreGraphicsFontStyle_Enum
#endif


@interface OrgMapsforgeCoreGraphicsFontStyle : JavaLangEnum

#pragma mark Public

+ (OrgMapsforgeCoreGraphicsFontStyle *)fromStringWithNSString:(NSString *)value;

+ (OrgMapsforgeCoreGraphicsFontStyle *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (OrgMapsforgeCoreGraphicsFontStyle_Enum)toNSEnum;

@property(readonly) OrgMapsforgeCoreGraphicsFontStyle_Enum enumValue;
+ (OrgMapsforgeCoreGraphicsFontStyle *)fromNSEnum:(OrgMapsforgeCoreGraphicsFontStyle_Enum)value;

- (OrgMapsforgeCoreGraphicsFontStyle_ORDINAL)ordinal NS_SWIFT_UNAVAILABLE("Use .enumValue");

- (nullable instancetype)initWithFontStyle:(OrgMapsforgeCoreGraphicsFontStyle_Enum)value;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreGraphicsFontStyle)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsFontStyle *OrgMapsforgeCoreGraphicsFontStyle_values_[];

inline OrgMapsforgeCoreGraphicsFontStyle *OrgMapsforgeCoreGraphicsFontStyle_get_BOLD(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsFontStyle, BOLD)

inline OrgMapsforgeCoreGraphicsFontStyle *OrgMapsforgeCoreGraphicsFontStyle_get_BOLD_ITALIC(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsFontStyle, BOLD_ITALIC)

inline OrgMapsforgeCoreGraphicsFontStyle *OrgMapsforgeCoreGraphicsFontStyle_get_ITALIC(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsFontStyle, ITALIC)

inline OrgMapsforgeCoreGraphicsFontStyle *OrgMapsforgeCoreGraphicsFontStyle_get_NORMAL(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsFontStyle, NORMAL)

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsFontStyle *OrgMapsforgeCoreGraphicsFontStyle_fromStringWithNSString_(NSString *value);

FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeCoreGraphicsFontStyle_values(void);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsFontStyle *OrgMapsforgeCoreGraphicsFontStyle_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsFontStyle *OrgMapsforgeCoreGraphicsFontStyle_fromOrdinal(OrgMapsforgeCoreGraphicsFontStyle_ORDINAL ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsFontStyle)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsFontStyle")
