//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/GraphicFactory.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsGraphicFactory")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsGraphicFactory
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsGraphicFactory 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsGraphicFactory 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsGraphicFactory

#if !defined (OrgMapsforgeCoreGraphicsGraphicFactory_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsGraphicFactory || defined(INCLUDE_OrgMapsforgeCoreGraphicsGraphicFactory))
#define OrgMapsforgeCoreGraphicsGraphicFactory_

@class IOSByteArray;
@class JavaIoInputStream;
@class JavaLangBoolean;
@class JavaLangDouble;
@class JavaLangFloat;
@class JavaLangInteger;
@class NSString;
@class OrgMapsforgeCoreGraphicsColor;
@class OrgMapsforgeCoreGraphicsDisplay;
@class OrgMapsforgeCoreGraphicsPosition;
@class OrgMapsforgeCoreMapelementsPointTextContainer;
@class OrgMapsforgeCoreMapelementsSymbolContainer;
@class OrgMapsforgeCoreModelBoundingBox;
@class OrgMapsforgeCoreModelPoint;
@protocol OrgMapsforgeCoreGraphicsBitmap;
@protocol OrgMapsforgeCoreGraphicsCanvas;
@protocol OrgMapsforgeCoreGraphicsHillshadingBitmap;
@protocol OrgMapsforgeCoreGraphicsMatrix;
@protocol OrgMapsforgeCoreGraphicsPaint;
@protocol OrgMapsforgeCoreGraphicsPath;
@protocol OrgMapsforgeCoreGraphicsResourceBitmap;
@protocol OrgMapsforgeCoreGraphicsTileBitmap;

@protocol OrgMapsforgeCoreGraphicsGraphicFactory < JavaObject >

- (id<OrgMapsforgeCoreGraphicsBitmap>)createBitmapWithInt:(jint)width
                                                  withInt:(jint)height;

- (id<OrgMapsforgeCoreGraphicsBitmap>)createBitmapWithInt:(jint)width
                                                  withInt:(jint)height
                                              withBoolean:(bool)isTransparent;

- (id<OrgMapsforgeCoreGraphicsCanvas>)createCanvas;

- (jint)createColorWithOrgMapsforgeCoreGraphicsColor:(OrgMapsforgeCoreGraphicsColor *)color;

- (jint)createColorWithInt:(jint)alpha
                   withInt:(jint)red
                   withInt:(jint)green
                   withInt:(jint)blue;

- (id<OrgMapsforgeCoreGraphicsMatrix>)createMatrix;

- (id<OrgMapsforgeCoreGraphicsHillshadingBitmap>)createMonoBitmapWithInt:(jint)width
                                                                 withInt:(jint)height
                                                           withByteArray:(IOSByteArray *)buffer
                                                                 withInt:(jint)padding
                                    withOrgMapsforgeCoreModelBoundingBox:(OrgMapsforgeCoreModelBoundingBox *)area
                                                                 withInt:(jint)color;

- (id<OrgMapsforgeCoreGraphicsPaint>)createPaint;

- (id<OrgMapsforgeCoreGraphicsPaint>)createPaintWithOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paint;

- (id<OrgMapsforgeCoreGraphicsPath>)createPath;

- (OrgMapsforgeCoreMapelementsPointTextContainer *)createPointTextContainerWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)xy
                                                                                               withDouble:(jdouble)horizontalOffset
                                                                                               withDouble:(jdouble)verticalOffset
                                                                      withOrgMapsforgeCoreGraphicsDisplay:(OrgMapsforgeCoreGraphicsDisplay *)display
                                                                                                  withInt:(jint)priority
                                                                                             withNSString:(NSString *)text
                                                                        withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paintFront
                                                                        withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paintBack
                                                           withOrgMapsforgeCoreMapelementsSymbolContainer:(OrgMapsforgeCoreMapelementsSymbolContainer *)symbolContainer
                                                                     withOrgMapsforgeCoreGraphicsPosition:(OrgMapsforgeCoreGraphicsPosition *)position
                                                                                                  withInt:(jint)maxTextWidth;

- (id<OrgMapsforgeCoreGraphicsResourceBitmap>)createResourceBitmapWithJavaIoInputStream:(JavaIoInputStream *)inputStream
                                                                              withFloat:(jfloat)scaleFactor
                                                                                withInt:(jint)width
                                                                                withInt:(jint)height
                                                                                withInt:(jint)percent
                                                                                withInt:(jint)hash_;

- (id<OrgMapsforgeCoreGraphicsTileBitmap>)createTileBitmapWithJavaIoInputStream:(JavaIoInputStream *)inputStream
                                                                        withInt:(jint)tileSize
                                                                    withBoolean:(bool)isTransparent;

- (id<OrgMapsforgeCoreGraphicsTileBitmap>)createTileBitmapWithInt:(jint)tileSize
                                                      withBoolean:(bool)isTransparent;

- (JavaIoInputStream *)platformSpecificSourcesWithNSString:(NSString *)relativePathPrefix
                                              withNSString:(NSString *)src;

- (id<OrgMapsforgeCoreGraphicsResourceBitmap>)renderSvgWithJavaIoInputStream:(JavaIoInputStream *)inputStream
                                                                   withFloat:(jfloat)scaleFactor
                                                                     withInt:(jint)width
                                                                     withInt:(jint)height
                                                                     withInt:(jint)percent
                                                                     withInt:(jint)hash_;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreGraphicsGraphicFactory)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsGraphicFactory)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsGraphicFactory")
