//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/GraphicContext.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsGraphicContext")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsGraphicContext
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsGraphicContext 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsGraphicContext 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsGraphicContext

#if !defined (OrgMapsforgeCoreGraphicsGraphicContext_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsGraphicContext || defined(INCLUDE_OrgMapsforgeCoreGraphicsGraphicContext))
#define OrgMapsforgeCoreGraphicsGraphicContext_

@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangFloat;
@class JavaLangInteger;
@class NSString;
@class OrgMapsforgeCoreGraphicsColor;
@class OrgMapsforgeCoreModelRectangle;
@protocol OrgMapsforgeCoreGraphicsBitmap;
@protocol OrgMapsforgeCoreGraphicsMatrix;
@protocol OrgMapsforgeCoreGraphicsPaint;
@protocol OrgMapsforgeCoreGraphicsPath;

@protocol OrgMapsforgeCoreGraphicsGraphicContext < JavaObject >

- (void)drawBitmapWithOrgMapsforgeCoreGraphicsBitmap:(id<OrgMapsforgeCoreGraphicsBitmap>)bitmap
                                             withInt:(jint)left
                                             withInt:(jint)top;

- (void)drawBitmapWithOrgMapsforgeCoreGraphicsBitmap:(id<OrgMapsforgeCoreGraphicsBitmap>)bitmap
                                             withInt:(jint)left
                                             withInt:(jint)top
                                           withFloat:(jfloat)alpha;

- (void)drawBitmapWithOrgMapsforgeCoreGraphicsBitmap:(id<OrgMapsforgeCoreGraphicsBitmap>)bitmap
                  withOrgMapsforgeCoreGraphicsMatrix:(id<OrgMapsforgeCoreGraphicsMatrix>)matrix;

- (void)drawBitmapWithOrgMapsforgeCoreGraphicsBitmap:(id<OrgMapsforgeCoreGraphicsBitmap>)bitmap
                  withOrgMapsforgeCoreGraphicsMatrix:(id<OrgMapsforgeCoreGraphicsMatrix>)matrix
                                           withFloat:(jfloat)alpha;

- (void)drawBitmapWithOrgMapsforgeCoreGraphicsBitmap:(id<OrgMapsforgeCoreGraphicsBitmap>)bitmap
                                             withInt:(jint)srcLeft
                                             withInt:(jint)srcTop
                                             withInt:(jint)srcRight
                                             withInt:(jint)srcBottom
                                             withInt:(jint)dstLeft
                                             withInt:(jint)dstTop
                                             withInt:(jint)dstRight
                                             withInt:(jint)dstBottom;

- (void)drawBitmapWithOrgMapsforgeCoreGraphicsBitmap:(id<OrgMapsforgeCoreGraphicsBitmap>)bitmap
                                             withInt:(jint)srcLeft
                                             withInt:(jint)srcTop
                                             withInt:(jint)srcRight
                                             withInt:(jint)srcBottom
                                             withInt:(jint)dstLeft
                                             withInt:(jint)dstTop
                                             withInt:(jint)dstRight
                                             withInt:(jint)dstBottom
                                           withFloat:(jfloat)alpha;

- (void)drawCircleWithInt:(jint)x
                  withInt:(jint)y
                  withInt:(jint)radius
withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paint;

- (void)drawLineWithInt:(jint)x1
                withInt:(jint)y1
                withInt:(jint)x2
                withInt:(jint)y2
withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paint;

- (void)drawPathWithOrgMapsforgeCoreGraphicsPath:(id<OrgMapsforgeCoreGraphicsPath>)path
               withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paint;

- (void)drawLinesWithOrgMapsforgeCoreModelPointArray2:(IOSObjectArray *)coordinates
                                            withFloat:(jfloat)dy
                    withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paint;

- (void)drawPathTextWithNSString:(NSString *)text
withOrgMapsforgeCoreGraphicsPath:(id<OrgMapsforgeCoreGraphicsPath>)path
withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paint;

- (void)drawTextWithNSString:(NSString *)text
                     withInt:(jint)x
                     withInt:(jint)y
withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paint;

- (void)drawTextRotatedWithNSString:(NSString *)text
                            withInt:(jint)x1
                            withInt:(jint)y1
                            withInt:(jint)x2
                            withInt:(jint)y2
  withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paint;

- (void)fillColorWithOrgMapsforgeCoreGraphicsColor:(OrgMapsforgeCoreGraphicsColor *)color;

- (void)fillColorWithInt:(jint)color;

- (bool)isAntiAlias;

- (bool)isFilterBitmap;

- (void)resetClip;

- (void)setAntiAliasWithBoolean:(bool)aa;

- (void)setClipWithInt:(jint)left
               withInt:(jint)top
               withInt:(jint)width
               withInt:(jint)height;

- (void)setClipWithInt:(jint)left
               withInt:(jint)top
               withInt:(jint)width
               withInt:(jint)height
           withBoolean:(bool)intersect;

- (void)setClipDifferenceWithFloat:(jfloat)left
                         withFloat:(jfloat)top
                         withFloat:(jfloat)width
                         withFloat:(jfloat)height;

- (void)setFilterBitmapWithBoolean:(bool)filter;

- (void)shadeBitmapWithOrgMapsforgeCoreGraphicsBitmap:(id<OrgMapsforgeCoreGraphicsBitmap>)bitmap
                   withOrgMapsforgeCoreModelRectangle:(OrgMapsforgeCoreModelRectangle *)shadeRect
                   withOrgMapsforgeCoreModelRectangle:(OrgMapsforgeCoreModelRectangle *)tileRect
                                            withFloat:(jfloat)magnitude
                                              withInt:(jint)color
                                          withBoolean:(bool)external;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreGraphicsGraphicContext)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsGraphicContext)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsGraphicContext")
