//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/HillshadingBitmap.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsHillshadingBitmap")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsHillshadingBitmap
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsHillshadingBitmap 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsHillshadingBitmap 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsHillshadingBitmap

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMapsforgeCoreGraphicsHillshadingBitmap_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsHillshadingBitmap || defined(INCLUDE_OrgMapsforgeCoreGraphicsHillshadingBitmap))
#define OrgMapsforgeCoreGraphicsHillshadingBitmap_

#define RESTRICT_OrgMapsforgeCoreGraphicsBitmap 1
#define INCLUDE_OrgMapsforgeCoreGraphicsBitmap 1
#include "org/mapsforge/core/graphics/Bitmap.h"

@class JavaLangInteger;
@class JavaLangLong;
@class OrgMapsforgeCoreModelBoundingBox;

@protocol OrgMapsforgeCoreGraphicsHillshadingBitmap < OrgMapsforgeCoreGraphicsBitmap, JavaObject >

- (OrgMapsforgeCoreModelBoundingBox *)getAreaRect;

- (jint)getPadding;

- (jlong)getSizeBytes;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreGraphicsHillshadingBitmap)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsHillshadingBitmap)


#endif

#if !defined (OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsHillshadingBitmap || defined(INCLUDE_OrgMapsforgeCoreGraphicsHillshadingBitmap_Border))
#define OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;
@class JavaLangBoolean;
@class NSString;

typedef NS_ENUM(jint, OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_Enum) {
  OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_Enum_WEST NS_SWIFT_NAME(west) = 0,
  OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_Enum_NORTH NS_SWIFT_NAME(north) = 1,
  OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_Enum_EAST NS_SWIFT_NAME(east) = 2,
  OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_Enum_SOUTH NS_SWIFT_NAME(south) = 3,
};

#if J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION
#define OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_ORDINAL jint
#else
#define OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_ORDINAL OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_Enum
#endif


@interface OrgMapsforgeCoreGraphicsHillshadingBitmap_Border : JavaLangEnum {
 @public
  bool vertical_;
}

#pragma mark Public

+ (OrgMapsforgeCoreGraphicsHillshadingBitmap_Border *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_Enum)toNSEnum;

@property(readonly) OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_Enum enumValue;
+ (OrgMapsforgeCoreGraphicsHillshadingBitmap_Border *)fromNSEnum:(OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_Enum)value;

- (OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_ORDINAL)ordinal NS_SWIFT_UNAVAILABLE("Use .enumValue");

- (nullable instancetype)initWithBorder:(OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_Enum)value;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreGraphicsHillshadingBitmap_Border)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsHillshadingBitmap_Border *OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_values_[];

inline OrgMapsforgeCoreGraphicsHillshadingBitmap_Border *OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_get_WEST(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsHillshadingBitmap_Border, WEST)

inline OrgMapsforgeCoreGraphicsHillshadingBitmap_Border *OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_get_NORTH(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsHillshadingBitmap_Border, NORTH)

inline OrgMapsforgeCoreGraphicsHillshadingBitmap_Border *OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_get_EAST(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsHillshadingBitmap_Border, EAST)

inline OrgMapsforgeCoreGraphicsHillshadingBitmap_Border *OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_get_SOUTH(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsHillshadingBitmap_Border, SOUTH)

FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_values(void);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsHillshadingBitmap_Border *OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsHillshadingBitmap_Border *OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_fromOrdinal(OrgMapsforgeCoreGraphicsHillshadingBitmap_Border_ORDINAL ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsHillshadingBitmap_Border)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsHillshadingBitmap")
