//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/util/IOUtils.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreUtilIOUtils")
#ifdef RESTRICT_OrgMapsforgeCoreUtilIOUtils
#define INCLUDE_ALL_OrgMapsforgeCoreUtilIOUtils 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreUtilIOUtils 1
#endif
#undef RESTRICT_OrgMapsforgeCoreUtilIOUtils

#if !defined (OrgMapsforgeCoreUtilIOUtils_) && (INCLUDE_ALL_OrgMapsforgeCoreUtilIOUtils || defined(INCLUDE_OrgMapsforgeCoreUtilIOUtils))
#define OrgMapsforgeCoreUtilIOUtils_

@protocol JavaIoCloseable;

@interface OrgMapsforgeCoreUtilIOUtils : NSObject

#pragma mark Public

+ (void)closeQuietlyWithJavaIoCloseable:(id<JavaIoCloseable>)closeable;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreUtilIOUtils)

FOUNDATION_EXPORT void OrgMapsforgeCoreUtilIOUtils_closeQuietlyWithJavaIoCloseable_(id<JavaIoCloseable> closeable);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreUtilIOUtils)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreUtilIOUtils")
