//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/model/LineString.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreModelLineString")
#ifdef RESTRICT_OrgMapsforgeCoreModelLineString
#define INCLUDE_ALL_OrgMapsforgeCoreModelLineString 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreModelLineString 1
#endif
#undef RESTRICT_OrgMapsforgeCoreModelLineString

#if !defined (OrgMapsforgeCoreModelLineString_) && (INCLUDE_ALL_OrgMapsforgeCoreModelLineString || defined(INCLUDE_OrgMapsforgeCoreModelLineString))
#define OrgMapsforgeCoreModelLineString_

@class JavaLangBoolean;
@class JavaLangDouble;
@class OrgMapsforgeCoreModelPoint;
@class OrgMapsforgeCoreModelRectangle;
@protocol JavaUtilList;

@interface OrgMapsforgeCoreModelLineString : NSObject {
 @public
  id<JavaUtilList> segments_;
}

#pragma mark Public

- (instancetype)init;

- (bool)isEqual:(id)obj;

- (OrgMapsforgeCoreModelLineString *)extractPartWithDouble:(jdouble)startDistance
                                                withDouble:(jdouble)endDistance;

- (OrgMapsforgeCoreModelRectangle *)getBounds;

- (OrgMapsforgeCoreModelPoint *)interpolateWithDouble:(jdouble)distance;

- (jdouble)length;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreModelLineString)

J2OBJC_FIELD_SETTER(OrgMapsforgeCoreModelLineString, segments_, id<JavaUtilList>)

FOUNDATION_EXPORT void OrgMapsforgeCoreModelLineString_init(OrgMapsforgeCoreModelLineString *self);

FOUNDATION_EXPORT OrgMapsforgeCoreModelLineString *new_OrgMapsforgeCoreModelLineString_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreModelLineString *create_OrgMapsforgeCoreModelLineString_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreModelLineString)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreModelLineString")
