//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/mapelements/MapElementContainer.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreMapelementsMapElementContainer")
#ifdef RESTRICT_OrgMapsforgeCoreMapelementsMapElementContainer
#define INCLUDE_ALL_OrgMapsforgeCoreMapelementsMapElementContainer 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreMapelementsMapElementContainer 1
#endif
#undef RESTRICT_OrgMapsforgeCoreMapelementsMapElementContainer

#if !defined (OrgMapsforgeCoreMapelementsMapElementContainer_) && (INCLUDE_ALL_OrgMapsforgeCoreMapelementsMapElementContainer || defined(INCLUDE_OrgMapsforgeCoreMapelementsMapElementContainer))
#define OrgMapsforgeCoreMapelementsMapElementContainer_

#define RESTRICT_JavaLangComparable 1
#define INCLUDE_JavaLangComparable 1
#include "java/lang/Comparable.h"

@class JavaLangBoolean;
@class JavaLangDouble;
@class JavaLangInteger;
@class NSString;
@class OrgMapsforgeCoreGraphicsDisplay;
@class OrgMapsforgeCoreModelPoint;
@class OrgMapsforgeCoreModelRectangle;
@class OrgMapsforgeCoreModelRotation;
@protocol OrgMapsforgeCoreGraphicsCanvas;
@protocol OrgMapsforgeCoreGraphicsMatrix;

@interface OrgMapsforgeCoreMapelementsMapElementContainer : NSObject < JavaLangComparable > {
 @public
  OrgMapsforgeCoreModelRectangle *boundaryAbsolute_;
  OrgMapsforgeCoreGraphicsDisplay *display_;
  jint priority_;
  OrgMapsforgeCoreModelPoint *xy_;
  volatile_jdouble clashRotationDegrees_;
  volatile_id clashRect_;
}

#pragma mark Public

- (bool)clashesWithWithOrgMapsforgeCoreMapelementsMapElementContainer:(OrgMapsforgeCoreMapelementsMapElementContainer *)other
                                    withOrgMapsforgeCoreModelRotation:(OrgMapsforgeCoreModelRotation *)rotation;

- (jint)compareToWithId:(OrgMapsforgeCoreMapelementsMapElementContainer *)other;

- (void)drawWithOrgMapsforgeCoreGraphicsCanvas:(id<OrgMapsforgeCoreGraphicsCanvas>)canvas
                withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)origin
            withOrgMapsforgeCoreGraphicsMatrix:(id<OrgMapsforgeCoreGraphicsMatrix>)matrix
             withOrgMapsforgeCoreModelRotation:(OrgMapsforgeCoreModelRotation *)rotation;

- (bool)isEqual:(id)obj;

- (OrgMapsforgeCoreModelRectangle *)getClashRectWithOrgMapsforgeCoreModelRotation:(OrgMapsforgeCoreModelRotation *)rotation;

- (OrgMapsforgeCoreModelPoint *)getPoint;

- (jint)getPriority;

- (NSUInteger)hash;

- (bool)intersectsWithOrgMapsforgeCoreModelRectangle:(OrgMapsforgeCoreModelRectangle *)rectangle
                   withOrgMapsforgeCoreModelRotation:(OrgMapsforgeCoreModelRotation *)rotation;

- (bool)isNotVisible;

- (NSString *)description;

#pragma mark Protected

- (instancetype)initWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)xy
               withOrgMapsforgeCoreGraphicsDisplay:(OrgMapsforgeCoreGraphicsDisplay *)display
                                           withInt:(jint)priority;

- (OrgMapsforgeCoreModelRectangle *)getBoundary;

- (OrgMapsforgeCoreModelRectangle *)getBoundaryAbsolute;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreMapelementsMapElementContainer)

J2OBJC_FIELD_SETTER(OrgMapsforgeCoreMapelementsMapElementContainer, boundaryAbsolute_, OrgMapsforgeCoreModelRectangle *)
J2OBJC_FIELD_SETTER(OrgMapsforgeCoreMapelementsMapElementContainer, display_, OrgMapsforgeCoreGraphicsDisplay *)
J2OBJC_FIELD_SETTER(OrgMapsforgeCoreMapelementsMapElementContainer, xy_, OrgMapsforgeCoreModelPoint *)
J2OBJC_VOLATILE_FIELD_SETTER(OrgMapsforgeCoreMapelementsMapElementContainer, clashRect_, OrgMapsforgeCoreModelRectangle *)

FOUNDATION_EXPORT void OrgMapsforgeCoreMapelementsMapElementContainer_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreGraphicsDisplay_withInt_(OrgMapsforgeCoreMapelementsMapElementContainer *self, OrgMapsforgeCoreModelPoint *xy, OrgMapsforgeCoreGraphicsDisplay *display, jint priority);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreMapelementsMapElementContainer)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreMapelementsMapElementContainer")
