//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/model/MapPosition.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreModelMapPosition")
#ifdef RESTRICT_OrgMapsforgeCoreModelMapPosition
#define INCLUDE_ALL_OrgMapsforgeCoreModelMapPosition 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreModelMapPosition 1
#endif
#undef RESTRICT_OrgMapsforgeCoreModelMapPosition

#if !defined (OrgMapsforgeCoreModelMapPosition_) && (INCLUDE_ALL_OrgMapsforgeCoreModelMapPosition || defined(INCLUDE_OrgMapsforgeCoreModelMapPosition))
#define OrgMapsforgeCoreModelMapPosition_

@class JavaLangBoolean;
@class JavaLangByte;
@class JavaLangDouble;
@class JavaLangInteger;
@class NSString;
@class OrgMapsforgeCoreModelLatLong;
@class OrgMapsforgeCoreModelRotation;

@interface OrgMapsforgeCoreModelMapPosition : NSObject {
 @public
  OrgMapsforgeCoreModelLatLong *latLong_;
  jdouble zoom_;
  jbyte zoomLevel_;
  OrgMapsforgeCoreModelRotation *rotation_;
}

#pragma mark Public

- (instancetype)initWithOrgMapsforgeCoreModelLatLong:(OrgMapsforgeCoreModelLatLong *)latLong
                                            withByte:(jbyte)zoomLevel;

- (instancetype)initWithOrgMapsforgeCoreModelLatLong:(OrgMapsforgeCoreModelLatLong *)latLong
                                          withDouble:(jdouble)zoom
                   withOrgMapsforgeCoreModelRotation:(OrgMapsforgeCoreModelRotation *)rotation;

- (bool)isEqual:(id)obj;

- (NSUInteger)hash;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreModelMapPosition)

J2OBJC_FIELD_SETTER(OrgMapsforgeCoreModelMapPosition, latLong_, OrgMapsforgeCoreModelLatLong *)
J2OBJC_FIELD_SETTER(OrgMapsforgeCoreModelMapPosition, rotation_, OrgMapsforgeCoreModelRotation *)

FOUNDATION_EXPORT void OrgMapsforgeCoreModelMapPosition_initWithOrgMapsforgeCoreModelLatLong_withByte_(OrgMapsforgeCoreModelMapPosition *self, OrgMapsforgeCoreModelLatLong *latLong, jbyte zoomLevel);

FOUNDATION_EXPORT OrgMapsforgeCoreModelMapPosition *new_OrgMapsforgeCoreModelMapPosition_initWithOrgMapsforgeCoreModelLatLong_withByte_(OrgMapsforgeCoreModelLatLong *latLong, jbyte zoomLevel) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreModelMapPosition *create_OrgMapsforgeCoreModelMapPosition_initWithOrgMapsforgeCoreModelLatLong_withByte_(OrgMapsforgeCoreModelLatLong *latLong, jbyte zoomLevel);

FOUNDATION_EXPORT void OrgMapsforgeCoreModelMapPosition_initWithOrgMapsforgeCoreModelLatLong_withDouble_withOrgMapsforgeCoreModelRotation_(OrgMapsforgeCoreModelMapPosition *self, OrgMapsforgeCoreModelLatLong *latLong, jdouble zoom, OrgMapsforgeCoreModelRotation *rotation);

FOUNDATION_EXPORT OrgMapsforgeCoreModelMapPosition *new_OrgMapsforgeCoreModelMapPosition_initWithOrgMapsforgeCoreModelLatLong_withDouble_withOrgMapsforgeCoreModelRotation_(OrgMapsforgeCoreModelLatLong *latLong, jdouble zoom, OrgMapsforgeCoreModelRotation *rotation) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreModelMapPosition *create_OrgMapsforgeCoreModelMapPosition_initWithOrgMapsforgeCoreModelLatLong_withDouble_withOrgMapsforgeCoreModelRotation_(OrgMapsforgeCoreModelLatLong *latLong, jdouble zoom, OrgMapsforgeCoreModelRotation *rotation);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreModelMapPosition)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreModelMapPosition")
