//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/Paint.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsPaint")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsPaint
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsPaint 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsPaint 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsPaint

#if !defined (OrgMapsforgeCoreGraphicsPaint_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsPaint || defined(INCLUDE_OrgMapsforgeCoreGraphicsPaint))
#define OrgMapsforgeCoreGraphicsPaint_

@class IOSFloatArray;
@class JavaLangBoolean;
@class JavaLangDouble;
@class JavaLangFloat;
@class JavaLangInteger;
@class NSString;
@class OrgMapsforgeCoreGraphicsAlign;
@class OrgMapsforgeCoreGraphicsCap;
@class OrgMapsforgeCoreGraphicsColor;
@class OrgMapsforgeCoreGraphicsFontFamily;
@class OrgMapsforgeCoreGraphicsFontStyle;
@class OrgMapsforgeCoreGraphicsJoin;
@class OrgMapsforgeCoreGraphicsStyle;
@class OrgMapsforgeCoreModelPoint;
@class OrgMapsforgeCoreModelRectangle;
@protocol OrgMapsforgeCoreGraphicsBitmap;

@protocol OrgMapsforgeCoreGraphicsPaint < JavaObject >

- (jint)getColor;

- (jfloat)getStrokeWidth;

- (OrgMapsforgeCoreModelRectangle *)getTextBoundsWithNSString:(NSString *)text;

- (jint)getTextHeightWithNSString:(NSString *)text;

- (jint)getTextWidthWithNSString:(NSString *)text;

- (bool)isTransparent;

- (bool)isComplexStyle;

- (void)setBitmapShaderWithOrgMapsforgeCoreGraphicsBitmap:(id<OrgMapsforgeCoreGraphicsBitmap>)bitmap;

- (void)setBitmapShaderShiftWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)origin;

- (void)setColorWithOrgMapsforgeCoreGraphicsColor:(OrgMapsforgeCoreGraphicsColor *)color;

- (void)setColorWithInt:(jint)color;

- (void)setDashPathEffectWithFloatArray:(IOSFloatArray *)strokeDasharray;

- (void)setStrokeCapWithOrgMapsforgeCoreGraphicsCap:(OrgMapsforgeCoreGraphicsCap *)cap;

- (void)setStrokeJoinWithOrgMapsforgeCoreGraphicsJoin:(OrgMapsforgeCoreGraphicsJoin *)join;

- (void)setStrokeWidthWithFloat:(jfloat)strokeWidth;

- (void)setStyleWithOrgMapsforgeCoreGraphicsStyle:(OrgMapsforgeCoreGraphicsStyle *)style;

- (void)setTextAlignWithOrgMapsforgeCoreGraphicsAlign:(OrgMapsforgeCoreGraphicsAlign *)align;

- (void)setTextSizeWithFloat:(jfloat)textSize;

- (void)setTypefaceWithOrgMapsforgeCoreGraphicsFontFamily:(OrgMapsforgeCoreGraphicsFontFamily *)fontFamily
                    withOrgMapsforgeCoreGraphicsFontStyle:(OrgMapsforgeCoreGraphicsFontStyle *)fontStyle;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreGraphicsPaint)

inline jdouble OrgMapsforgeCoreGraphicsPaint_get_FONT_PADDING_FACTOR(void);
#define OrgMapsforgeCoreGraphicsPaint_FONT_PADDING_FACTOR 0.2
J2OBJC_STATIC_FIELD_CONSTANT(OrgMapsforgeCoreGraphicsPaint, FONT_PADDING_FACTOR, jdouble)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsPaint)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsPaint")
