//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/mapelements/PointTextContainer.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreMapelementsPointTextContainer")
#ifdef RESTRICT_OrgMapsforgeCoreMapelementsPointTextContainer
#define INCLUDE_ALL_OrgMapsforgeCoreMapelementsPointTextContainer 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreMapelementsPointTextContainer 1
#endif
#undef RESTRICT_OrgMapsforgeCoreMapelementsPointTextContainer

#if !defined (OrgMapsforgeCoreMapelementsPointTextContainer_) && (INCLUDE_ALL_OrgMapsforgeCoreMapelementsPointTextContainer || defined(INCLUDE_OrgMapsforgeCoreMapelementsPointTextContainer))
#define OrgMapsforgeCoreMapelementsPointTextContainer_

#define RESTRICT_OrgMapsforgeCoreMapelementsMapElementContainer 1
#define INCLUDE_OrgMapsforgeCoreMapelementsMapElementContainer 1
#include "org/mapsforge/core/mapelements/MapElementContainer.h"

@class JavaLangBoolean;
@class JavaLangDouble;
@class JavaLangInteger;
@class NSString;
@class OrgMapsforgeCoreGraphicsDisplay;
@class OrgMapsforgeCoreGraphicsPosition;
@class OrgMapsforgeCoreMapelementsSymbolContainer;
@class OrgMapsforgeCoreModelPoint;
@class OrgMapsforgeCoreModelRectangle;
@class OrgMapsforgeCoreModelRotation;
@protocol OrgMapsforgeCoreGraphicsPaint;

@interface OrgMapsforgeCoreMapelementsPointTextContainer : OrgMapsforgeCoreMapelementsMapElementContainer {
 @public
  jdouble horizontalOffset_;
  bool isNotVisible_;
  jint maxTextWidth_;
  id<OrgMapsforgeCoreGraphicsPaint> paintBack_;
  id<OrgMapsforgeCoreGraphicsPaint> paintFront_;
  OrgMapsforgeCoreGraphicsPosition *position_;
  OrgMapsforgeCoreMapelementsSymbolContainer *symbolContainer_;
  NSString *text_;
  jdouble verticalOffset_;
}

#pragma mark Public

- (bool)clashesWithWithOrgMapsforgeCoreMapelementsMapElementContainer:(OrgMapsforgeCoreMapelementsMapElementContainer *)other
                                    withOrgMapsforgeCoreModelRotation:(OrgMapsforgeCoreModelRotation *)rotation;

- (bool)isEqual:(id)obj;

- (OrgMapsforgeCoreModelRectangle *)getClashRectWithOrgMapsforgeCoreModelRotation:(OrgMapsforgeCoreModelRotation *)rotation;

+ (OrgMapsforgeCoreModelRectangle *)getClashRectangleTransformedWithOrgMapsforgeCoreMapelementsPointTextContainer:(OrgMapsforgeCoreMapelementsPointTextContainer *)pointTextContainer
                                                                                                       withDouble:(jdouble)originX
                                                                                                       withDouble:(jdouble)originY
                                                                                withOrgMapsforgeCoreModelRotation:(OrgMapsforgeCoreModelRotation *)rotation;

+ (OrgMapsforgeCoreModelPoint *)getRotatedRelativePositionWithOrgMapsforgeCoreMapelementsPointTextContainer:(OrgMapsforgeCoreMapelementsPointTextContainer *)pointTextContainer
                                                                                                 withDouble:(jdouble)originX
                                                                                                 withDouble:(jdouble)originY
                                                                          withOrgMapsforgeCoreModelRotation:(OrgMapsforgeCoreModelRotation *)rotation;

- (NSUInteger)hash;

- (bool)isNotVisible;

- (NSString *)description;

#pragma mark Protected

- (instancetype)initWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)point
                                        withDouble:(jdouble)horizontalOffset
                                        withDouble:(jdouble)verticalOffset
               withOrgMapsforgeCoreGraphicsDisplay:(OrgMapsforgeCoreGraphicsDisplay *)display
                                           withInt:(jint)priority
                                      withNSString:(NSString *)text
                 withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paintFront
                 withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paintBack
    withOrgMapsforgeCoreMapelementsSymbolContainer:(OrgMapsforgeCoreMapelementsSymbolContainer *)symbolContainer
              withOrgMapsforgeCoreGraphicsPosition:(OrgMapsforgeCoreGraphicsPosition *)position
                                           withInt:(jint)maxTextWidth;

- (OrgMapsforgeCoreModelRectangle *)getBoundaryAbsolute;

- (OrgMapsforgeCoreModelPoint *)getRotatedRelativePositionWithDouble:(jdouble)originX
                                                          withDouble:(jdouble)originY
                                   withOrgMapsforgeCoreModelRotation:(OrgMapsforgeCoreModelRotation *)rotation;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)arg0
               withOrgMapsforgeCoreGraphicsDisplay:(OrgMapsforgeCoreGraphicsDisplay *)arg1
                                           withInt:(jint)arg2 NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreMapelementsPointTextContainer)

J2OBJC_FIELD_SETTER(OrgMapsforgeCoreMapelementsPointTextContainer, paintBack_, id<OrgMapsforgeCoreGraphicsPaint>)
J2OBJC_FIELD_SETTER(OrgMapsforgeCoreMapelementsPointTextContainer, paintFront_, id<OrgMapsforgeCoreGraphicsPaint>)
J2OBJC_FIELD_SETTER(OrgMapsforgeCoreMapelementsPointTextContainer, position_, OrgMapsforgeCoreGraphicsPosition *)
J2OBJC_FIELD_SETTER(OrgMapsforgeCoreMapelementsPointTextContainer, symbolContainer_, OrgMapsforgeCoreMapelementsSymbolContainer *)
J2OBJC_FIELD_SETTER(OrgMapsforgeCoreMapelementsPointTextContainer, text_, NSString *)

inline bool OrgMapsforgeCoreMapelementsPointTextContainer_get_DEBUG_CLASH_BOUNDS(void);
#define OrgMapsforgeCoreMapelementsPointTextContainer_DEBUG_CLASH_BOUNDS false
J2OBJC_STATIC_FIELD_CONSTANT(OrgMapsforgeCoreMapelementsPointTextContainer, DEBUG_CLASH_BOUNDS, bool)

FOUNDATION_EXPORT void OrgMapsforgeCoreMapelementsPointTextContainer_initWithOrgMapsforgeCoreModelPoint_withDouble_withDouble_withOrgMapsforgeCoreGraphicsDisplay_withInt_withNSString_withOrgMapsforgeCoreGraphicsPaint_withOrgMapsforgeCoreGraphicsPaint_withOrgMapsforgeCoreMapelementsSymbolContainer_withOrgMapsforgeCoreGraphicsPosition_withInt_(OrgMapsforgeCoreMapelementsPointTextContainer *self, OrgMapsforgeCoreModelPoint *point, jdouble horizontalOffset, jdouble verticalOffset, OrgMapsforgeCoreGraphicsDisplay *display, jint priority, NSString *text, id<OrgMapsforgeCoreGraphicsPaint> paintFront, id<OrgMapsforgeCoreGraphicsPaint> paintBack, OrgMapsforgeCoreMapelementsSymbolContainer *symbolContainer, OrgMapsforgeCoreGraphicsPosition *position, jint maxTextWidth);

FOUNDATION_EXPORT OrgMapsforgeCoreModelPoint *OrgMapsforgeCoreMapelementsPointTextContainer_getRotatedRelativePositionWithOrgMapsforgeCoreMapelementsPointTextContainer_withDouble_withDouble_withOrgMapsforgeCoreModelRotation_(OrgMapsforgeCoreMapelementsPointTextContainer *pointTextContainer, jdouble originX, jdouble originY, OrgMapsforgeCoreModelRotation *rotation);

FOUNDATION_EXPORT OrgMapsforgeCoreModelRectangle *OrgMapsforgeCoreMapelementsPointTextContainer_getClashRectangleTransformedWithOrgMapsforgeCoreMapelementsPointTextContainer_withDouble_withDouble_withOrgMapsforgeCoreModelRotation_(OrgMapsforgeCoreMapelementsPointTextContainer *pointTextContainer, jdouble originX, jdouble originY, OrgMapsforgeCoreModelRotation *rotation);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreMapelementsPointTextContainer)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreMapelementsPointTextContainer")
