//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/Position.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsPosition")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsPosition
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsPosition 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsPosition 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsPosition

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMapsforgeCoreGraphicsPosition_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsPosition || defined(INCLUDE_OrgMapsforgeCoreGraphicsPosition))
#define OrgMapsforgeCoreGraphicsPosition_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;
@class JavaLangBoolean;
@class NSString;

typedef NS_ENUM(jint, OrgMapsforgeCoreGraphicsPosition_Enum) {
  OrgMapsforgeCoreGraphicsPosition_Enum_AUTO NS_SWIFT_NAME(auto_) = 0,
  OrgMapsforgeCoreGraphicsPosition_Enum_CENTER NS_SWIFT_NAME(center) = 1,
  OrgMapsforgeCoreGraphicsPosition_Enum_BELOW NS_SWIFT_NAME(below) = 2,
  OrgMapsforgeCoreGraphicsPosition_Enum_BELOW_LEFT NS_SWIFT_NAME(belowLeft) = 3,
  OrgMapsforgeCoreGraphicsPosition_Enum_BELOW_RIGHT NS_SWIFT_NAME(belowRight) = 4,
  OrgMapsforgeCoreGraphicsPosition_Enum_ABOVE NS_SWIFT_NAME(above) = 5,
  OrgMapsforgeCoreGraphicsPosition_Enum_ABOVE_LEFT NS_SWIFT_NAME(aboveLeft) = 6,
  OrgMapsforgeCoreGraphicsPosition_Enum_ABOVE_RIGHT NS_SWIFT_NAME(aboveRight) = 7,
  OrgMapsforgeCoreGraphicsPosition_Enum_LEFT NS_SWIFT_NAME(left) = 8,
  OrgMapsforgeCoreGraphicsPosition_Enum_RIGHT NS_SWIFT_NAME(right) = 9,
};

#if J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION
#define OrgMapsforgeCoreGraphicsPosition_ORDINAL jint
#else
#define OrgMapsforgeCoreGraphicsPosition_ORDINAL OrgMapsforgeCoreGraphicsPosition_Enum
#endif


@interface OrgMapsforgeCoreGraphicsPosition : JavaLangEnum

#pragma mark Public

+ (OrgMapsforgeCoreGraphicsPosition *)fromStringWithNSString:(NSString *)value;

- (bool)isOnLeftSide;

- (bool)isOnLowerSide;

- (bool)isOnRightSide;

- (bool)isOnUpperSide;

+ (OrgMapsforgeCoreGraphicsPosition *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (OrgMapsforgeCoreGraphicsPosition_Enum)toNSEnum;

@property(readonly) OrgMapsforgeCoreGraphicsPosition_Enum enumValue;
+ (OrgMapsforgeCoreGraphicsPosition *)fromNSEnum:(OrgMapsforgeCoreGraphicsPosition_Enum)value;

- (OrgMapsforgeCoreGraphicsPosition_ORDINAL)ordinal NS_SWIFT_UNAVAILABLE("Use .enumValue");

- (nullable instancetype)initWithPosition:(OrgMapsforgeCoreGraphicsPosition_Enum)value;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreGraphicsPosition)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_values_[];

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_AUTO(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, AUTO)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_CENTER(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, CENTER)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_BELOW(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, BELOW)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_BELOW_LEFT(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, BELOW_LEFT)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_BELOW_RIGHT(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, BELOW_RIGHT)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_ABOVE(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, ABOVE)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_ABOVE_LEFT(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, ABOVE_LEFT)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_ABOVE_RIGHT(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, ABOVE_RIGHT)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_LEFT(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, LEFT)

inline OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_get_RIGHT(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsPosition, RIGHT)

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_fromStringWithNSString_(NSString *value);

FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeCoreGraphicsPosition_values(void);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_fromOrdinal(OrgMapsforgeCoreGraphicsPosition_ORDINAL ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsPosition)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsPosition")
