//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/ResourceBitmap.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsResourceBitmap")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsResourceBitmap
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsResourceBitmap 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsResourceBitmap 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsResourceBitmap

#if !defined (OrgMapsforgeCoreGraphicsResourceBitmap_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsResourceBitmap || defined(INCLUDE_OrgMapsforgeCoreGraphicsResourceBitmap))
#define OrgMapsforgeCoreGraphicsResourceBitmap_

#define RESTRICT_OrgMapsforgeCoreGraphicsBitmap 1
#define INCLUDE_OrgMapsforgeCoreGraphicsBitmap 1
#include "org/mapsforge/core/graphics/Bitmap.h"

@protocol OrgMapsforgeCoreGraphicsResourceBitmap < OrgMapsforgeCoreGraphicsBitmap, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreGraphicsResourceBitmap)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsResourceBitmap)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsResourceBitmap")
