//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/model/Rotation.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreModelRotation")
#ifdef RESTRICT_OrgMapsforgeCoreModelRotation
#define INCLUDE_ALL_OrgMapsforgeCoreModelRotation 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreModelRotation 1
#endif
#undef RESTRICT_OrgMapsforgeCoreModelRotation

#if !defined (OrgMapsforgeCoreModelRotation_) && (INCLUDE_ALL_OrgMapsforgeCoreModelRotation || defined(INCLUDE_OrgMapsforgeCoreModelRotation))
#define OrgMapsforgeCoreModelRotation_

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class JavaLangBoolean;
@class JavaLangDouble;
@class JavaLangFloat;
@class JavaLangInteger;
@class NSString;
@class OrgMapsforgeCoreModelPoint;
@class OrgMapsforgeCoreModelRectangle;

@interface OrgMapsforgeCoreModelRotation : NSObject < JavaIoSerializable > {
 @public
  jfloat degrees_;
  jfloat px_;
  jfloat py_;
  jdouble radians_;
}

#pragma mark Public

- (instancetype)initWithFloat:(jfloat)degrees
                    withFloat:(jfloat)px
                    withFloat:(jfloat)py;

- (bool)isEqual:(id)obj;

- (NSUInteger)hash;

+ (bool)noRotationWithOrgMapsforgeCoreModelRotation:(OrgMapsforgeCoreModelRotation *)rotation;

- (OrgMapsforgeCoreModelRotation *)reverseRotation;

- (OrgMapsforgeCoreModelPoint *)rotateWithDouble:(jdouble)x
                                      withDouble:(jdouble)y;

- (OrgMapsforgeCoreModelPoint *)rotateWithDouble:(jdouble)x
                                      withDouble:(jdouble)y
                                     withBoolean:(bool)reverse;

- (OrgMapsforgeCoreModelPoint *)rotateWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)p;

- (OrgMapsforgeCoreModelPoint *)rotateWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)p
                                                         withBoolean:(bool)reverse;

- (OrgMapsforgeCoreModelRectangle *)rotateWithOrgMapsforgeCoreModelRectangle:(OrgMapsforgeCoreModelRectangle *)r;

- (OrgMapsforgeCoreModelRectangle *)rotateWithOrgMapsforgeCoreModelRectangle:(OrgMapsforgeCoreModelRectangle *)r
                                                                 withBoolean:(bool)reverse;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreModelRotation)

inline OrgMapsforgeCoreModelRotation *OrgMapsforgeCoreModelRotation_get_NULL_ROTATION(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgMapsforgeCoreModelRotation *OrgMapsforgeCoreModelRotation_NULL_ROTATION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMapsforgeCoreModelRotation, NULL_ROTATION, OrgMapsforgeCoreModelRotation *)

FOUNDATION_EXPORT bool OrgMapsforgeCoreModelRotation_noRotationWithOrgMapsforgeCoreModelRotation_(OrgMapsforgeCoreModelRotation *rotation);

FOUNDATION_EXPORT void OrgMapsforgeCoreModelRotation_initWithFloat_withFloat_withFloat_(OrgMapsforgeCoreModelRotation *self, jfloat degrees, jfloat px, jfloat py);

FOUNDATION_EXPORT OrgMapsforgeCoreModelRotation *new_OrgMapsforgeCoreModelRotation_initWithFloat_withFloat_withFloat_(jfloat degrees, jfloat px, jfloat py) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreModelRotation *create_OrgMapsforgeCoreModelRotation_initWithFloat_withFloat_withFloat_(jfloat degrees, jfloat px, jfloat py);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreModelRotation)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreModelRotation")
