//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/mapelements/SymbolContainer.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreMapelementsSymbolContainer")
#ifdef RESTRICT_OrgMapsforgeCoreMapelementsSymbolContainer
#define INCLUDE_ALL_OrgMapsforgeCoreMapelementsSymbolContainer 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreMapelementsSymbolContainer 1
#endif
#undef RESTRICT_OrgMapsforgeCoreMapelementsSymbolContainer

#if !defined (OrgMapsforgeCoreMapelementsSymbolContainer_) && (INCLUDE_ALL_OrgMapsforgeCoreMapelementsSymbolContainer || defined(INCLUDE_OrgMapsforgeCoreMapelementsSymbolContainer))
#define OrgMapsforgeCoreMapelementsSymbolContainer_

#define RESTRICT_OrgMapsforgeCoreMapelementsMapElementContainer 1
#define INCLUDE_OrgMapsforgeCoreMapelementsMapElementContainer 1
#include "org/mapsforge/core/mapelements/MapElementContainer.h"

@class JavaLangBoolean;
@class JavaLangFloat;
@class JavaLangInteger;
@class OrgMapsforgeCoreGraphicsDisplay;
@class OrgMapsforgeCoreModelPoint;
@class OrgMapsforgeCoreModelRectangle;
@class OrgMapsforgeCoreModelRotation;
@protocol OrgMapsforgeCoreGraphicsBitmap;
@protocol OrgMapsforgeCoreGraphicsCanvas;
@protocol OrgMapsforgeCoreGraphicsMatrix;

@interface OrgMapsforgeCoreMapelementsSymbolContainer : OrgMapsforgeCoreMapelementsMapElementContainer {
 @public
  OrgMapsforgeCoreModelRectangle *boundary_;
  bool alignCanvas_;
  id<OrgMapsforgeCoreGraphicsBitmap> symbol_;
  jfloat theta_;
}

#pragma mark Public

- (instancetype)initWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)point
               withOrgMapsforgeCoreGraphicsDisplay:(OrgMapsforgeCoreGraphicsDisplay *)display
                                           withInt:(jint)priority
                withOrgMapsforgeCoreModelRectangle:(OrgMapsforgeCoreModelRectangle *)boundary
                withOrgMapsforgeCoreGraphicsBitmap:(id<OrgMapsforgeCoreGraphicsBitmap>)symbol
                                       withBoolean:(bool)alignCanvas;

- (instancetype)initWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)point
               withOrgMapsforgeCoreGraphicsDisplay:(OrgMapsforgeCoreGraphicsDisplay *)display
                                           withInt:(jint)priority
                withOrgMapsforgeCoreModelRectangle:(OrgMapsforgeCoreModelRectangle *)boundary
                withOrgMapsforgeCoreGraphicsBitmap:(id<OrgMapsforgeCoreGraphicsBitmap>)symbol
                                         withFloat:(jfloat)theta
                                       withBoolean:(bool)alignCanvas;

- (void)drawWithOrgMapsforgeCoreGraphicsCanvas:(id<OrgMapsforgeCoreGraphicsCanvas>)canvas
                withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)origin
            withOrgMapsforgeCoreGraphicsMatrix:(id<OrgMapsforgeCoreGraphicsMatrix>)matrix
             withOrgMapsforgeCoreModelRotation:(OrgMapsforgeCoreModelRotation *)rotation;

- (bool)isEqual:(id)obj;

- (NSUInteger)hash;

#pragma mark Protected

- (OrgMapsforgeCoreModelRectangle *)getBoundary;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)arg0
               withOrgMapsforgeCoreGraphicsDisplay:(OrgMapsforgeCoreGraphicsDisplay *)arg1
                                           withInt:(jint)arg2 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreMapelementsSymbolContainer)

J2OBJC_FIELD_SETTER(OrgMapsforgeCoreMapelementsSymbolContainer, boundary_, OrgMapsforgeCoreModelRectangle *)
J2OBJC_FIELD_SETTER(OrgMapsforgeCoreMapelementsSymbolContainer, symbol_, id<OrgMapsforgeCoreGraphicsBitmap>)

FOUNDATION_EXPORT void OrgMapsforgeCoreMapelementsSymbolContainer_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreGraphicsDisplay_withInt_withOrgMapsforgeCoreModelRectangle_withOrgMapsforgeCoreGraphicsBitmap_withBoolean_(OrgMapsforgeCoreMapelementsSymbolContainer *self, OrgMapsforgeCoreModelPoint *point, OrgMapsforgeCoreGraphicsDisplay *display, jint priority, OrgMapsforgeCoreModelRectangle *boundary, id<OrgMapsforgeCoreGraphicsBitmap> symbol, bool alignCanvas);

FOUNDATION_EXPORT OrgMapsforgeCoreMapelementsSymbolContainer *new_OrgMapsforgeCoreMapelementsSymbolContainer_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreGraphicsDisplay_withInt_withOrgMapsforgeCoreModelRectangle_withOrgMapsforgeCoreGraphicsBitmap_withBoolean_(OrgMapsforgeCoreModelPoint *point, OrgMapsforgeCoreGraphicsDisplay *display, jint priority, OrgMapsforgeCoreModelRectangle *boundary, id<OrgMapsforgeCoreGraphicsBitmap> symbol, bool alignCanvas) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreMapelementsSymbolContainer *create_OrgMapsforgeCoreMapelementsSymbolContainer_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreGraphicsDisplay_withInt_withOrgMapsforgeCoreModelRectangle_withOrgMapsforgeCoreGraphicsBitmap_withBoolean_(OrgMapsforgeCoreModelPoint *point, OrgMapsforgeCoreGraphicsDisplay *display, jint priority, OrgMapsforgeCoreModelRectangle *boundary, id<OrgMapsforgeCoreGraphicsBitmap> symbol, bool alignCanvas);

FOUNDATION_EXPORT void OrgMapsforgeCoreMapelementsSymbolContainer_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreGraphicsDisplay_withInt_withOrgMapsforgeCoreModelRectangle_withOrgMapsforgeCoreGraphicsBitmap_withFloat_withBoolean_(OrgMapsforgeCoreMapelementsSymbolContainer *self, OrgMapsforgeCoreModelPoint *point, OrgMapsforgeCoreGraphicsDisplay *display, jint priority, OrgMapsforgeCoreModelRectangle *boundary, id<OrgMapsforgeCoreGraphicsBitmap> symbol, jfloat theta, bool alignCanvas);

FOUNDATION_EXPORT OrgMapsforgeCoreMapelementsSymbolContainer *new_OrgMapsforgeCoreMapelementsSymbolContainer_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreGraphicsDisplay_withInt_withOrgMapsforgeCoreModelRectangle_withOrgMapsforgeCoreGraphicsBitmap_withFloat_withBoolean_(OrgMapsforgeCoreModelPoint *point, OrgMapsforgeCoreGraphicsDisplay *display, jint priority, OrgMapsforgeCoreModelRectangle *boundary, id<OrgMapsforgeCoreGraphicsBitmap> symbol, jfloat theta, bool alignCanvas) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreMapelementsSymbolContainer *create_OrgMapsforgeCoreMapelementsSymbolContainer_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreGraphicsDisplay_withInt_withOrgMapsforgeCoreModelRectangle_withOrgMapsforgeCoreGraphicsBitmap_withFloat_withBoolean_(OrgMapsforgeCoreModelPoint *point, OrgMapsforgeCoreGraphicsDisplay *display, jint priority, OrgMapsforgeCoreModelRectangle *boundary, id<OrgMapsforgeCoreGraphicsBitmap> symbol, jfloat theta, bool alignCanvas);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreMapelementsSymbolContainer)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreMapelementsSymbolContainer")
