//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/SymbolOrientation.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsSymbolOrientation")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsSymbolOrientation
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsSymbolOrientation 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsSymbolOrientation 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsSymbolOrientation

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMapsforgeCoreGraphicsSymbolOrientation_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsSymbolOrientation || defined(INCLUDE_OrgMapsforgeCoreGraphicsSymbolOrientation))
#define OrgMapsforgeCoreGraphicsSymbolOrientation_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;
@class NSString;

typedef NS_ENUM(jint, OrgMapsforgeCoreGraphicsSymbolOrientation_Enum) {
  OrgMapsforgeCoreGraphicsSymbolOrientation_Enum_AUTO NS_SWIFT_NAME(auto_) = 0,
  OrgMapsforgeCoreGraphicsSymbolOrientation_Enum_AUTO_DOWN NS_SWIFT_NAME(autoDown) = 1,
  OrgMapsforgeCoreGraphicsSymbolOrientation_Enum_RIGHT NS_SWIFT_NAME(right) = 2,
  OrgMapsforgeCoreGraphicsSymbolOrientation_Enum_LEFT NS_SWIFT_NAME(left) = 3,
  OrgMapsforgeCoreGraphicsSymbolOrientation_Enum_UP NS_SWIFT_NAME(up) = 4,
  OrgMapsforgeCoreGraphicsSymbolOrientation_Enum_DOWN NS_SWIFT_NAME(down) = 5,
};

#if J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION
#define OrgMapsforgeCoreGraphicsSymbolOrientation_ORDINAL jint
#else
#define OrgMapsforgeCoreGraphicsSymbolOrientation_ORDINAL OrgMapsforgeCoreGraphicsSymbolOrientation_Enum
#endif


@interface OrgMapsforgeCoreGraphicsSymbolOrientation : JavaLangEnum

#pragma mark Public

+ (OrgMapsforgeCoreGraphicsSymbolOrientation *)fromStringWithNSString:(NSString *)value;

+ (OrgMapsforgeCoreGraphicsSymbolOrientation *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (OrgMapsforgeCoreGraphicsSymbolOrientation_Enum)toNSEnum;

@property(readonly) OrgMapsforgeCoreGraphicsSymbolOrientation_Enum enumValue;
+ (OrgMapsforgeCoreGraphicsSymbolOrientation *)fromNSEnum:(OrgMapsforgeCoreGraphicsSymbolOrientation_Enum)value;

- (OrgMapsforgeCoreGraphicsSymbolOrientation_ORDINAL)ordinal NS_SWIFT_UNAVAILABLE("Use .enumValue");

- (nullable instancetype)initWithSymbolOrientation:(OrgMapsforgeCoreGraphicsSymbolOrientation_Enum)value;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreGraphicsSymbolOrientation)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsSymbolOrientation *OrgMapsforgeCoreGraphicsSymbolOrientation_values_[];

inline OrgMapsforgeCoreGraphicsSymbolOrientation *OrgMapsforgeCoreGraphicsSymbolOrientation_get_AUTO(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsSymbolOrientation, AUTO)

inline OrgMapsforgeCoreGraphicsSymbolOrientation *OrgMapsforgeCoreGraphicsSymbolOrientation_get_AUTO_DOWN(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsSymbolOrientation, AUTO_DOWN)

inline OrgMapsforgeCoreGraphicsSymbolOrientation *OrgMapsforgeCoreGraphicsSymbolOrientation_get_RIGHT(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsSymbolOrientation, RIGHT)

inline OrgMapsforgeCoreGraphicsSymbolOrientation *OrgMapsforgeCoreGraphicsSymbolOrientation_get_LEFT(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsSymbolOrientation, LEFT)

inline OrgMapsforgeCoreGraphicsSymbolOrientation *OrgMapsforgeCoreGraphicsSymbolOrientation_get_UP(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsSymbolOrientation, UP)

inline OrgMapsforgeCoreGraphicsSymbolOrientation *OrgMapsforgeCoreGraphicsSymbolOrientation_get_DOWN(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsSymbolOrientation, DOWN)

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsSymbolOrientation *OrgMapsforgeCoreGraphicsSymbolOrientation_fromStringWithNSString_(NSString *value);

FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeCoreGraphicsSymbolOrientation_values(void);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsSymbolOrientation *OrgMapsforgeCoreGraphicsSymbolOrientation_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsSymbolOrientation *OrgMapsforgeCoreGraphicsSymbolOrientation_fromOrdinal(OrgMapsforgeCoreGraphicsSymbolOrientation_ORDINAL ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsSymbolOrientation)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsSymbolOrientation")
