//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/TextTransform.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsTextTransform")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsTextTransform
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsTextTransform 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsTextTransform 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsTextTransform

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMapsforgeCoreGraphicsTextTransform_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsTextTransform || defined(INCLUDE_OrgMapsforgeCoreGraphicsTextTransform))
#define OrgMapsforgeCoreGraphicsTextTransform_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;
@class NSString;

typedef NS_ENUM(jint, OrgMapsforgeCoreGraphicsTextTransform_Enum) {
  OrgMapsforgeCoreGraphicsTextTransform_Enum_NONE NS_SWIFT_NAME(none) = 0,
  OrgMapsforgeCoreGraphicsTextTransform_Enum_UPPERCASE NS_SWIFT_NAME(uppercase) = 1,
  OrgMapsforgeCoreGraphicsTextTransform_Enum_LOWERCASE NS_SWIFT_NAME(lowercase) = 2,
  OrgMapsforgeCoreGraphicsTextTransform_Enum_CAPITALIZE NS_SWIFT_NAME(capitalize) = 3,
};

#if J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION
#define OrgMapsforgeCoreGraphicsTextTransform_ORDINAL jint
#else
#define OrgMapsforgeCoreGraphicsTextTransform_ORDINAL OrgMapsforgeCoreGraphicsTextTransform_Enum
#endif


@interface OrgMapsforgeCoreGraphicsTextTransform : JavaLangEnum

#pragma mark Public

+ (OrgMapsforgeCoreGraphicsTextTransform *)fromStringWithNSString:(NSString *)value;

+ (OrgMapsforgeCoreGraphicsTextTransform *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (OrgMapsforgeCoreGraphicsTextTransform_Enum)toNSEnum;

@property(readonly) OrgMapsforgeCoreGraphicsTextTransform_Enum enumValue;
+ (OrgMapsforgeCoreGraphicsTextTransform *)fromNSEnum:(OrgMapsforgeCoreGraphicsTextTransform_Enum)value;

- (OrgMapsforgeCoreGraphicsTextTransform_ORDINAL)ordinal NS_SWIFT_UNAVAILABLE("Use .enumValue");

- (nullable instancetype)initWithTextTransform:(OrgMapsforgeCoreGraphicsTextTransform_Enum)value;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreGraphicsTextTransform)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsTextTransform *OrgMapsforgeCoreGraphicsTextTransform_values_[];

inline OrgMapsforgeCoreGraphicsTextTransform *OrgMapsforgeCoreGraphicsTextTransform_get_NONE(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsTextTransform, NONE)

inline OrgMapsforgeCoreGraphicsTextTransform *OrgMapsforgeCoreGraphicsTextTransform_get_UPPERCASE(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsTextTransform, UPPERCASE)

inline OrgMapsforgeCoreGraphicsTextTransform *OrgMapsforgeCoreGraphicsTextTransform_get_LOWERCASE(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsTextTransform, LOWERCASE)

inline OrgMapsforgeCoreGraphicsTextTransform *OrgMapsforgeCoreGraphicsTextTransform_get_CAPITALIZE(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsTextTransform, CAPITALIZE)

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsTextTransform *OrgMapsforgeCoreGraphicsTextTransform_fromStringWithNSString_(NSString *value);

FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeCoreGraphicsTextTransform_values(void);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsTextTransform *OrgMapsforgeCoreGraphicsTextTransform_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsTextTransform *OrgMapsforgeCoreGraphicsTextTransform_fromOrdinal(OrgMapsforgeCoreGraphicsTextTransform_ORDINAL ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsTextTransform)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsTextTransform")
