//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/util/Utils.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreUtilUtils")
#ifdef RESTRICT_OrgMapsforgeCoreUtilUtils
#define INCLUDE_ALL_OrgMapsforgeCoreUtilUtils 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreUtilUtils 1
#endif
#undef RESTRICT_OrgMapsforgeCoreUtilUtils

#if !defined (OrgMapsforgeCoreUtilUtils_) && (INCLUDE_ALL_OrgMapsforgeCoreUtilUtils || defined(INCLUDE_OrgMapsforgeCoreUtilUtils))
#define OrgMapsforgeCoreUtilUtils_

@class IOSIntArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol JavaUtilCollection;
@protocol JavaUtilList;

@interface OrgMapsforgeCoreUtilUtils : NSObject

#pragma mark Public

+ (bool)containsWithIntArray:(IOSIntArray *)data
                     withInt:(jint)item;

+ (IOSIntArray *)convertListStringWithJavaUtilList:(id<JavaUtilList>)list;

+ (id<JavaUtilCollection>)deduplicateWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

+ (id<JavaUtilCollection>)deduplicateSortedWithJavaUtilCollection:(id<JavaUtilCollection>)sortedCollection;

+ (bool)equalsWithId:(id)o1
              withId:(id)o2;

+ (jint)hashTagParameterWithNSString:(NSString *)keyValue;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreUtilUtils)

FOUNDATION_EXPORT bool OrgMapsforgeCoreUtilUtils_equalsWithId_withId_(id o1, id o2);

FOUNDATION_EXPORT jint OrgMapsforgeCoreUtilUtils_hashTagParameterWithNSString_(NSString *keyValue);

FOUNDATION_EXPORT IOSIntArray *OrgMapsforgeCoreUtilUtils_convertListStringWithJavaUtilList_(id<JavaUtilList> list);

FOUNDATION_EXPORT bool OrgMapsforgeCoreUtilUtils_containsWithIntArray_withInt_(IOSIntArray *data, jint item);

FOUNDATION_EXPORT id<JavaUtilCollection> OrgMapsforgeCoreUtilUtils_deduplicateWithJavaUtilCollection_(id<JavaUtilCollection> collection);

FOUNDATION_EXPORT id<JavaUtilCollection> OrgMapsforgeCoreUtilUtils_deduplicateSortedWithJavaUtilCollection_(id<JavaUtilCollection> sortedCollection);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreUtilUtils)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreUtilUtils")
