//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/Curve.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsCurve")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsCurve
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsCurve 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsCurve 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsCurve

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMapsforgeCoreGraphicsCurve_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsCurve || defined(INCLUDE_OrgMapsforgeCoreGraphicsCurve))
#define OrgMapsforgeCoreGraphicsCurve_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;
@class NSString;

typedef NS_ENUM(jint, OrgMapsforgeCoreGraphicsCurve_Enum) {
  OrgMapsforgeCoreGraphicsCurve_Enum_NO NS_SWIFT_NAME(no) = 0,
  OrgMapsforgeCoreGraphicsCurve_Enum_CUBIC NS_SWIFT_NAME(cubic) = 1,
};

#if J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION
#define OrgMapsforgeCoreGraphicsCurve_ORDINAL jint
#else
#define OrgMapsforgeCoreGraphicsCurve_ORDINAL OrgMapsforgeCoreGraphicsCurve_Enum
#endif


@interface OrgMapsforgeCoreGraphicsCurve : JavaLangEnum

#pragma mark Public

+ (OrgMapsforgeCoreGraphicsCurve *)fromStringWithNSString:(NSString *)value;

+ (OrgMapsforgeCoreGraphicsCurve *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (OrgMapsforgeCoreGraphicsCurve_Enum)toNSEnum;

@property(readonly) OrgMapsforgeCoreGraphicsCurve_Enum enumValue;
+ (OrgMapsforgeCoreGraphicsCurve *)fromNSEnum:(OrgMapsforgeCoreGraphicsCurve_Enum)value;

- (OrgMapsforgeCoreGraphicsCurve_ORDINAL)ordinal NS_SWIFT_UNAVAILABLE("Use .enumValue");

- (nullable instancetype)initWithCurve:(OrgMapsforgeCoreGraphicsCurve_Enum)value;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreGraphicsCurve)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsCurve *OrgMapsforgeCoreGraphicsCurve_values_[];

inline OrgMapsforgeCoreGraphicsCurve *OrgMapsforgeCoreGraphicsCurve_get_NO(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsCurve, NO)

inline OrgMapsforgeCoreGraphicsCurve *OrgMapsforgeCoreGraphicsCurve_get_CUBIC(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsCurve, CUBIC)

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsCurve *OrgMapsforgeCoreGraphicsCurve_fromStringWithNSString_(NSString *value);

FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeCoreGraphicsCurve_values(void);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsCurve *OrgMapsforgeCoreGraphicsCurve_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsCurve *OrgMapsforgeCoreGraphicsCurve_fromOrdinal(OrgMapsforgeCoreGraphicsCurve_ORDINAL ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsCurve)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsCurve")
