//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/model/Dimension.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreModelDimension")
#ifdef RESTRICT_OrgMapsforgeCoreModelDimension
#define INCLUDE_ALL_OrgMapsforgeCoreModelDimension 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreModelDimension 1
#endif
#undef RESTRICT_OrgMapsforgeCoreModelDimension

#if !defined (OrgMapsforgeCoreModelDimension_) && (INCLUDE_ALL_OrgMapsforgeCoreModelDimension || defined(INCLUDE_OrgMapsforgeCoreModelDimension))
#define OrgMapsforgeCoreModelDimension_

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@class OrgMapsforgeCoreModelPoint;

@interface OrgMapsforgeCoreModelDimension : NSObject < JavaIoSerializable > {
 @public
  jint height_;
  jint width_;
}

#pragma mark Public

- (instancetype)initWithInt:(jint)width
                    withInt:(jint)height;

- (bool)isEqual:(id)obj;

- (OrgMapsforgeCoreModelPoint *)getCenter;

- (NSUInteger)hash;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreModelDimension)

FOUNDATION_EXPORT void OrgMapsforgeCoreModelDimension_initWithInt_withInt_(OrgMapsforgeCoreModelDimension *self, jint width, jint height);

FOUNDATION_EXPORT OrgMapsforgeCoreModelDimension *new_OrgMapsforgeCoreModelDimension_initWithInt_withInt_(jint width, jint height) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreModelDimension *create_OrgMapsforgeCoreModelDimension_initWithInt_withInt_(jint width, jint height);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreModelDimension)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreModelDimension")
