//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/Join.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsJoin")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsJoin
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsJoin 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsJoin 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsJoin

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMapsforgeCoreGraphicsJoin_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsJoin || defined(INCLUDE_OrgMapsforgeCoreGraphicsJoin))
#define OrgMapsforgeCoreGraphicsJoin_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;
@class NSString;

typedef NS_ENUM(jint, OrgMapsforgeCoreGraphicsJoin_Enum) {
  OrgMapsforgeCoreGraphicsJoin_Enum_BEVEL NS_SWIFT_NAME(bevel) = 0,
  OrgMapsforgeCoreGraphicsJoin_Enum_MITER NS_SWIFT_NAME(miter) = 1,
  OrgMapsforgeCoreGraphicsJoin_Enum_ROUND NS_SWIFT_NAME(round) = 2,
};

#if J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION
#define OrgMapsforgeCoreGraphicsJoin_ORDINAL jint
#else
#define OrgMapsforgeCoreGraphicsJoin_ORDINAL OrgMapsforgeCoreGraphicsJoin_Enum
#endif


@interface OrgMapsforgeCoreGraphicsJoin : JavaLangEnum

#pragma mark Public

+ (OrgMapsforgeCoreGraphicsJoin *)fromStringWithNSString:(NSString *)value;

+ (OrgMapsforgeCoreGraphicsJoin *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (OrgMapsforgeCoreGraphicsJoin_Enum)toNSEnum;

@property(readonly) OrgMapsforgeCoreGraphicsJoin_Enum enumValue;
+ (OrgMapsforgeCoreGraphicsJoin *)fromNSEnum:(OrgMapsforgeCoreGraphicsJoin_Enum)value;

- (OrgMapsforgeCoreGraphicsJoin_ORDINAL)ordinal NS_SWIFT_UNAVAILABLE("Use .enumValue");

- (nullable instancetype)initWithJoin:(OrgMapsforgeCoreGraphicsJoin_Enum)value;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreGraphicsJoin)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsJoin *OrgMapsforgeCoreGraphicsJoin_values_[];

inline OrgMapsforgeCoreGraphicsJoin *OrgMapsforgeCoreGraphicsJoin_get_BEVEL(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsJoin, BEVEL)

inline OrgMapsforgeCoreGraphicsJoin *OrgMapsforgeCoreGraphicsJoin_get_MITER(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsJoin, MITER)

inline OrgMapsforgeCoreGraphicsJoin *OrgMapsforgeCoreGraphicsJoin_get_ROUND(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsJoin, ROUND)

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsJoin *OrgMapsforgeCoreGraphicsJoin_fromStringWithNSString_(NSString *value);

FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeCoreGraphicsJoin_values(void);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsJoin *OrgMapsforgeCoreGraphicsJoin_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsJoin *OrgMapsforgeCoreGraphicsJoin_fromOrdinal(OrgMapsforgeCoreGraphicsJoin_ORDINAL ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsJoin)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsJoin")
