//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/model/LineSegment.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreModelLineSegment")
#ifdef RESTRICT_OrgMapsforgeCoreModelLineSegment
#define INCLUDE_ALL_OrgMapsforgeCoreModelLineSegment 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreModelLineSegment 1
#endif
#undef RESTRICT_OrgMapsforgeCoreModelLineSegment

#if !defined (OrgMapsforgeCoreModelLineSegment_) && (INCLUDE_ALL_OrgMapsforgeCoreModelLineSegment || defined(INCLUDE_OrgMapsforgeCoreModelLineSegment))
#define OrgMapsforgeCoreModelLineSegment_

@class JavaLangBoolean;
@class JavaLangDouble;
@class JavaLangInteger;
@class NSString;
@class OrgMapsforgeCoreModelPoint;
@class OrgMapsforgeCoreModelRectangle;

@interface OrgMapsforgeCoreModelLineSegment : NSObject {
 @public
  OrgMapsforgeCoreModelPoint *start_;
  OrgMapsforgeCoreModelPoint *end_;
}

#pragma mark Public

- (instancetype)initWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)start
                    withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)end;

- (instancetype)initWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)start
                    withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)direction
                                        withDouble:(jdouble)distance;

- (jdouble)angleToWithOrgMapsforgeCoreModelLineSegment:(OrgMapsforgeCoreModelLineSegment *)other;

- (OrgMapsforgeCoreModelLineSegment *)clipToRectangleWithOrgMapsforgeCoreModelRectangle:(OrgMapsforgeCoreModelRectangle *)r;

- (bool)isEqual:(id)obj;

- (NSUInteger)hash;

- (bool)intersectsRectangleWithOrgMapsforgeCoreModelRectangle:(OrgMapsforgeCoreModelRectangle *)r
                                                  withBoolean:(bool)bias;

- (jdouble)length;

- (OrgMapsforgeCoreModelPoint *)pointAlongLineSegmentWithDouble:(jdouble)distance;

- (OrgMapsforgeCoreModelLineSegment *)reverse;

- (OrgMapsforgeCoreModelLineSegment *)subSegmentWithDouble:(jdouble)offset
                                                withDouble:(jdouble)length;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreModelLineSegment)

J2OBJC_FIELD_SETTER(OrgMapsforgeCoreModelLineSegment, start_, OrgMapsforgeCoreModelPoint *)
J2OBJC_FIELD_SETTER(OrgMapsforgeCoreModelLineSegment, end_, OrgMapsforgeCoreModelPoint *)

FOUNDATION_EXPORT void OrgMapsforgeCoreModelLineSegment_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_(OrgMapsforgeCoreModelLineSegment *self, OrgMapsforgeCoreModelPoint *start, OrgMapsforgeCoreModelPoint *end);

FOUNDATION_EXPORT OrgMapsforgeCoreModelLineSegment *new_OrgMapsforgeCoreModelLineSegment_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_(OrgMapsforgeCoreModelPoint *start, OrgMapsforgeCoreModelPoint *end) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreModelLineSegment *create_OrgMapsforgeCoreModelLineSegment_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_(OrgMapsforgeCoreModelPoint *start, OrgMapsforgeCoreModelPoint *end);

FOUNDATION_EXPORT void OrgMapsforgeCoreModelLineSegment_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_withDouble_(OrgMapsforgeCoreModelLineSegment *self, OrgMapsforgeCoreModelPoint *start, OrgMapsforgeCoreModelPoint *direction, jdouble distance);

FOUNDATION_EXPORT OrgMapsforgeCoreModelLineSegment *new_OrgMapsforgeCoreModelLineSegment_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_withDouble_(OrgMapsforgeCoreModelPoint *start, OrgMapsforgeCoreModelPoint *direction, jdouble distance) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreModelLineSegment *create_OrgMapsforgeCoreModelLineSegment_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_withDouble_(OrgMapsforgeCoreModelPoint *start, OrgMapsforgeCoreModelPoint *direction, jdouble distance);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreModelLineSegment)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreModelLineSegment")
