//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/Path.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsPath")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsPath
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsPath 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsPath 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsPath

#if !defined (OrgMapsforgeCoreGraphicsPath_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsPath || defined(INCLUDE_OrgMapsforgeCoreGraphicsPath))
#define OrgMapsforgeCoreGraphicsPath_

@class JavaLangBoolean;
@class JavaLangFloat;
@class OrgMapsforgeCoreGraphicsFillRule;

@protocol OrgMapsforgeCoreGraphicsPath < JavaObject >

- (void)clear;

- (void)close;

- (bool)isEmpty;

- (void)lineToWithFloat:(jfloat)x
              withFloat:(jfloat)y;

- (void)moveToWithFloat:(jfloat)x
              withFloat:(jfloat)y;

- (void)quadToWithFloat:(jfloat)x1
              withFloat:(jfloat)y1
              withFloat:(jfloat)x2
              withFloat:(jfloat)y2;

- (void)setFillRuleWithOrgMapsforgeCoreGraphicsFillRule:(OrgMapsforgeCoreGraphicsFillRule *)fillRule;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreGraphicsPath)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsPath)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsPath")
