//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/model/Rectangle.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreModelRectangle")
#ifdef RESTRICT_OrgMapsforgeCoreModelRectangle
#define INCLUDE_ALL_OrgMapsforgeCoreModelRectangle 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreModelRectangle 1
#endif
#undef RESTRICT_OrgMapsforgeCoreModelRectangle

#if !defined (OrgMapsforgeCoreModelRectangle_) && (INCLUDE_ALL_OrgMapsforgeCoreModelRectangle || defined(INCLUDE_OrgMapsforgeCoreModelRectangle))
#define OrgMapsforgeCoreModelRectangle_

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class JavaLangBoolean;
@class JavaLangDouble;
@class JavaLangInteger;
@class NSString;
@class OrgMapsforgeCoreModelPoint;
@class OrgMapsforgeCoreModelRotation;

@interface OrgMapsforgeCoreModelRectangle : NSObject < JavaIoSerializable > {
 @public
  jdouble bottom_;
  jdouble left_;
  jdouble right_;
  jdouble top_;
}

#pragma mark Public

- (instancetype)initWithDouble:(jdouble)left
                    withDouble:(jdouble)top
                    withDouble:(jdouble)right
                    withDouble:(jdouble)bottom;

- (instancetype)initWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)a
                    withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)b
                    withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)c
                    withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)d;

- (OrgMapsforgeCoreModelRectangle *)clampClipCoordinatesWithDouble:(jdouble)horizontal
                                                        withDouble:(jdouble)vertical;

- (bool)containsWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)point;

- (bool)containsWithOrgMapsforgeCoreModelRectangle:(OrgMapsforgeCoreModelRectangle *)rectangle;

- (OrgMapsforgeCoreModelRectangle *)enlargeWithDouble:(jdouble)left
                                           withDouble:(jdouble)top
                                           withDouble:(jdouble)right
                                           withDouble:(jdouble)bottom;

- (OrgMapsforgeCoreModelRectangle *)envelopeWithDouble:(jdouble)padding;

- (bool)isEqual:(id)obj;

- (OrgMapsforgeCoreModelPoint *)getCenter;

- (jdouble)getCenterX;

- (jdouble)getCenterY;

- (jdouble)getHeight;

- (jdouble)getWidth;

- (NSUInteger)hash;

- (bool)intersectsWithOrgMapsforgeCoreModelRectangle:(OrgMapsforgeCoreModelRectangle *)rectangle;

- (bool)intersectsCircleWithDouble:(jdouble)pointX
                        withDouble:(jdouble)pointY
                        withDouble:(jdouble)radius;

- (OrgMapsforgeCoreModelRectangle *)rotateWithOrgMapsforgeCoreModelRotation:(OrgMapsforgeCoreModelRotation *)rotation;

- (OrgMapsforgeCoreModelRectangle *)shiftWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)origin;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreModelRectangle)

FOUNDATION_EXPORT void OrgMapsforgeCoreModelRectangle_initWithDouble_withDouble_withDouble_withDouble_(OrgMapsforgeCoreModelRectangle *self, jdouble left, jdouble top, jdouble right, jdouble bottom);

FOUNDATION_EXPORT OrgMapsforgeCoreModelRectangle *new_OrgMapsforgeCoreModelRectangle_initWithDouble_withDouble_withDouble_withDouble_(jdouble left, jdouble top, jdouble right, jdouble bottom) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreModelRectangle *create_OrgMapsforgeCoreModelRectangle_initWithDouble_withDouble_withDouble_withDouble_(jdouble left, jdouble top, jdouble right, jdouble bottom);

FOUNDATION_EXPORT void OrgMapsforgeCoreModelRectangle_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_(OrgMapsforgeCoreModelRectangle *self, OrgMapsforgeCoreModelPoint *a, OrgMapsforgeCoreModelPoint *b, OrgMapsforgeCoreModelPoint *c, OrgMapsforgeCoreModelPoint *d);

FOUNDATION_EXPORT OrgMapsforgeCoreModelRectangle *new_OrgMapsforgeCoreModelRectangle_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_(OrgMapsforgeCoreModelPoint *a, OrgMapsforgeCoreModelPoint *b, OrgMapsforgeCoreModelPoint *c, OrgMapsforgeCoreModelPoint *d) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreModelRectangle *create_OrgMapsforgeCoreModelRectangle_initWithOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_withOrgMapsforgeCoreModelPoint_(OrgMapsforgeCoreModelPoint *a, OrgMapsforgeCoreModelPoint *b, OrgMapsforgeCoreModelPoint *c, OrgMapsforgeCoreModelPoint *d);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreModelRectangle)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreModelRectangle")
