//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/Style.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsStyle")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsStyle
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsStyle 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsStyle 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsStyle

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMapsforgeCoreGraphicsStyle_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsStyle || defined(INCLUDE_OrgMapsforgeCoreGraphicsStyle))
#define OrgMapsforgeCoreGraphicsStyle_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;
@class NSString;

typedef NS_ENUM(jint, OrgMapsforgeCoreGraphicsStyle_Enum) {
  OrgMapsforgeCoreGraphicsStyle_Enum_FILL NS_SWIFT_NAME(fill) = 0,
  OrgMapsforgeCoreGraphicsStyle_Enum_STROKE NS_SWIFT_NAME(stroke) = 1,
};

#if J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION
#define OrgMapsforgeCoreGraphicsStyle_ORDINAL jint
#else
#define OrgMapsforgeCoreGraphicsStyle_ORDINAL OrgMapsforgeCoreGraphicsStyle_Enum
#endif


@interface OrgMapsforgeCoreGraphicsStyle : JavaLangEnum

#pragma mark Public

+ (OrgMapsforgeCoreGraphicsStyle *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (OrgMapsforgeCoreGraphicsStyle_Enum)toNSEnum;

@property(readonly) OrgMapsforgeCoreGraphicsStyle_Enum enumValue;
+ (OrgMapsforgeCoreGraphicsStyle *)fromNSEnum:(OrgMapsforgeCoreGraphicsStyle_Enum)value;

- (OrgMapsforgeCoreGraphicsStyle_ORDINAL)ordinal NS_SWIFT_UNAVAILABLE("Use .enumValue");

- (nullable instancetype)initWithStyle:(OrgMapsforgeCoreGraphicsStyle_Enum)value;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreGraphicsStyle)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsStyle *OrgMapsforgeCoreGraphicsStyle_values_[];

inline OrgMapsforgeCoreGraphicsStyle *OrgMapsforgeCoreGraphicsStyle_get_FILL(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsStyle, FILL)

inline OrgMapsforgeCoreGraphicsStyle *OrgMapsforgeCoreGraphicsStyle_get_STROKE(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsStyle, STROKE)

FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeCoreGraphicsStyle_values(void);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsStyle *OrgMapsforgeCoreGraphicsStyle_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsStyle *OrgMapsforgeCoreGraphicsStyle_fromOrdinal(OrgMapsforgeCoreGraphicsStyle_ORDINAL ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsStyle)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsStyle")
