//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/model/Tag.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreModelTag")
#ifdef RESTRICT_OrgMapsforgeCoreModelTag
#define INCLUDE_ALL_OrgMapsforgeCoreModelTag 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreModelTag 1
#endif
#undef RESTRICT_OrgMapsforgeCoreModelTag

#if !defined (OrgMapsforgeCoreModelTag_) && (INCLUDE_ALL_OrgMapsforgeCoreModelTag || defined(INCLUDE_OrgMapsforgeCoreModelTag))
#define OrgMapsforgeCoreModelTag_

#define RESTRICT_JavaLangComparable 1
#define INCLUDE_JavaLangComparable 1
#include "java/lang/Comparable.h"

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class JavaLangBoolean;
@class JavaLangCharacter;
@class JavaLangInteger;
@class NSString;

@interface OrgMapsforgeCoreModelTag : NSObject < JavaLangComparable, JavaIoSerializable > {
 @public
  NSString *key_;
  jint keyCode_;
  NSString *value_;
  jint valueCode_;
}

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)tag;

- (instancetype)initWithNSString:(NSString *)key
                    withNSString:(NSString *)value;

- (jint)compareToWithId:(OrgMapsforgeCoreModelTag *)other;

- (bool)isEqual:(id)obj;

- (NSUInteger)hash;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreModelTag)

J2OBJC_FIELD_SETTER(OrgMapsforgeCoreModelTag, key_, NSString *)
J2OBJC_FIELD_SETTER(OrgMapsforgeCoreModelTag, value_, NSString *)

inline jchar OrgMapsforgeCoreModelTag_get_KEY_VALUE_SEPARATOR(void);
#define OrgMapsforgeCoreModelTag_KEY_VALUE_SEPARATOR '='
J2OBJC_STATIC_FIELD_CONSTANT(OrgMapsforgeCoreModelTag, KEY_VALUE_SEPARATOR, jchar)

FOUNDATION_EXPORT void OrgMapsforgeCoreModelTag_initWithNSString_(OrgMapsforgeCoreModelTag *self, NSString *tag);

FOUNDATION_EXPORT OrgMapsforgeCoreModelTag *new_OrgMapsforgeCoreModelTag_initWithNSString_(NSString *tag) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreModelTag *create_OrgMapsforgeCoreModelTag_initWithNSString_(NSString *tag);

FOUNDATION_EXPORT void OrgMapsforgeCoreModelTag_initWithNSString_withNSString_(OrgMapsforgeCoreModelTag *self, NSString *key, NSString *value);

FOUNDATION_EXPORT OrgMapsforgeCoreModelTag *new_OrgMapsforgeCoreModelTag_initWithNSString_withNSString_(NSString *key, NSString *value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreModelTag *create_OrgMapsforgeCoreModelTag_initWithNSString_withNSString_(NSString *key, NSString *value);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreModelTag)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreModelTag")
