//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/TextOrientation.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsTextOrientation")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsTextOrientation
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsTextOrientation 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsTextOrientation 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsTextOrientation

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMapsforgeCoreGraphicsTextOrientation_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsTextOrientation || defined(INCLUDE_OrgMapsforgeCoreGraphicsTextOrientation))
#define OrgMapsforgeCoreGraphicsTextOrientation_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;
@class NSString;

typedef NS_ENUM(jint, OrgMapsforgeCoreGraphicsTextOrientation_Enum) {
  OrgMapsforgeCoreGraphicsTextOrientation_Enum_AUTO NS_SWIFT_NAME(auto_) = 0,
  OrgMapsforgeCoreGraphicsTextOrientation_Enum_AUTO_DOWN NS_SWIFT_NAME(autoDown) = 1,
  OrgMapsforgeCoreGraphicsTextOrientation_Enum_RIGHT NS_SWIFT_NAME(right) = 2,
  OrgMapsforgeCoreGraphicsTextOrientation_Enum_LEFT NS_SWIFT_NAME(left) = 3,
};

#if J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION
#define OrgMapsforgeCoreGraphicsTextOrientation_ORDINAL jint
#else
#define OrgMapsforgeCoreGraphicsTextOrientation_ORDINAL OrgMapsforgeCoreGraphicsTextOrientation_Enum
#endif


@interface OrgMapsforgeCoreGraphicsTextOrientation : JavaLangEnum

#pragma mark Public

+ (OrgMapsforgeCoreGraphicsTextOrientation *)fromStringWithNSString:(NSString *)value;

+ (OrgMapsforgeCoreGraphicsTextOrientation *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (OrgMapsforgeCoreGraphicsTextOrientation_Enum)toNSEnum;

@property(readonly) OrgMapsforgeCoreGraphicsTextOrientation_Enum enumValue;
+ (OrgMapsforgeCoreGraphicsTextOrientation *)fromNSEnum:(OrgMapsforgeCoreGraphicsTextOrientation_Enum)value;

- (OrgMapsforgeCoreGraphicsTextOrientation_ORDINAL)ordinal NS_SWIFT_UNAVAILABLE("Use .enumValue");

- (nullable instancetype)initWithTextOrientation:(OrgMapsforgeCoreGraphicsTextOrientation_Enum)value;

@end

J2OBJC_STATIC_INIT(OrgMapsforgeCoreGraphicsTextOrientation)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsTextOrientation *OrgMapsforgeCoreGraphicsTextOrientation_values_[];

inline OrgMapsforgeCoreGraphicsTextOrientation *OrgMapsforgeCoreGraphicsTextOrientation_get_AUTO(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsTextOrientation, AUTO)

inline OrgMapsforgeCoreGraphicsTextOrientation *OrgMapsforgeCoreGraphicsTextOrientation_get_AUTO_DOWN(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsTextOrientation, AUTO_DOWN)

inline OrgMapsforgeCoreGraphicsTextOrientation *OrgMapsforgeCoreGraphicsTextOrientation_get_RIGHT(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsTextOrientation, RIGHT)

inline OrgMapsforgeCoreGraphicsTextOrientation *OrgMapsforgeCoreGraphicsTextOrientation_get_LEFT(void);
J2OBJC_ENUM_CONSTANT(OrgMapsforgeCoreGraphicsTextOrientation, LEFT)

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsTextOrientation *OrgMapsforgeCoreGraphicsTextOrientation_fromStringWithNSString_(NSString *value);

FOUNDATION_EXPORT IOSObjectArray *OrgMapsforgeCoreGraphicsTextOrientation_values(void);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsTextOrientation *OrgMapsforgeCoreGraphicsTextOrientation_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT OrgMapsforgeCoreGraphicsTextOrientation *OrgMapsforgeCoreGraphicsTextOrientation_fromOrdinal(OrgMapsforgeCoreGraphicsTextOrientation_ORDINAL ordinal);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsTextOrientation)


#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsTextOrientation")
