//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/model/Tile.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreModelTile")
#ifdef RESTRICT_OrgMapsforgeCoreModelTile
#define INCLUDE_ALL_OrgMapsforgeCoreModelTile 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreModelTile 1
#endif
#undef RESTRICT_OrgMapsforgeCoreModelTile

#if !defined (OrgMapsforgeCoreModelTile_) && (INCLUDE_ALL_OrgMapsforgeCoreModelTile || defined(INCLUDE_OrgMapsforgeCoreModelTile))
#define OrgMapsforgeCoreModelTile_

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class JavaLangBoolean;
@class JavaLangByte;
@class JavaLangInteger;
@class JavaLangLong;
@class NSString;
@class OrgMapsforgeCoreModelBoundingBox;
@class OrgMapsforgeCoreModelPoint;
@class OrgMapsforgeCoreModelRectangle;
@protocol JavaUtilSet;

@interface OrgMapsforgeCoreModelTile : NSObject < JavaIoSerializable > {
 @public
  jlong mapSize_;
  jint tileSize_;
  jint tileX_;
  jint tileY_;
  jbyte zoomLevel_;
}

#pragma mark Public

- (instancetype)initWithInt:(jint)tileX
                    withInt:(jint)tileY
                   withByte:(jbyte)zoomLevel
                    withInt:(jint)tileSize;

- (bool)isEqual:(id)obj;

- (OrgMapsforgeCoreModelTile *)getAbove;

- (OrgMapsforgeCoreModelTile *)getAboveLeft;

- (OrgMapsforgeCoreModelTile *)getAboveRight;

- (OrgMapsforgeCoreModelTile *)getBelow;

- (OrgMapsforgeCoreModelTile *)getBelowLeft;

- (OrgMapsforgeCoreModelTile *)getBelowRight;

- (OrgMapsforgeCoreModelRectangle *)getBoundaryAbsolute;

+ (OrgMapsforgeCoreModelRectangle *)getBoundaryAbsoluteWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)upperLeft
                                                       withOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)lowerRight;

- (OrgMapsforgeCoreModelRectangle *)getBoundaryRelative;

- (OrgMapsforgeCoreModelBoundingBox *)getBoundingBox;

+ (OrgMapsforgeCoreModelBoundingBox *)getBoundingBoxWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)upperLeft
                                                    withOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)lowerRight;

- (OrgMapsforgeCoreModelTile *)getLeft;

+ (jint)getMaxTileNumberWithByte:(jbyte)zoomLevel;

- (id<JavaUtilSet>)getNeighbours;

- (OrgMapsforgeCoreModelPoint *)getOrigin;

- (OrgMapsforgeCoreModelTile *)getParent;

- (OrgMapsforgeCoreModelTile *)getRight;

- (jint)getShiftXWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)otherTile;

- (jint)getShiftYWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)otherTile;

- (NSUInteger)hash;

+ (bool)tileAreasOverlapWithOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)upperLeft
                        withOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)lowerRight
                        withOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)upperLeftOther
                        withOrgMapsforgeCoreModelTile:(OrgMapsforgeCoreModelTile *)lowerRightOther;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreModelTile)

FOUNDATION_EXPORT OrgMapsforgeCoreModelBoundingBox *OrgMapsforgeCoreModelTile_getBoundingBoxWithOrgMapsforgeCoreModelTile_withOrgMapsforgeCoreModelTile_(OrgMapsforgeCoreModelTile *upperLeft, OrgMapsforgeCoreModelTile *lowerRight);

FOUNDATION_EXPORT OrgMapsforgeCoreModelRectangle *OrgMapsforgeCoreModelTile_getBoundaryAbsoluteWithOrgMapsforgeCoreModelTile_withOrgMapsforgeCoreModelTile_(OrgMapsforgeCoreModelTile *upperLeft, OrgMapsforgeCoreModelTile *lowerRight);

FOUNDATION_EXPORT bool OrgMapsforgeCoreModelTile_tileAreasOverlapWithOrgMapsforgeCoreModelTile_withOrgMapsforgeCoreModelTile_withOrgMapsforgeCoreModelTile_withOrgMapsforgeCoreModelTile_(OrgMapsforgeCoreModelTile *upperLeft, OrgMapsforgeCoreModelTile *lowerRight, OrgMapsforgeCoreModelTile *upperLeftOther, OrgMapsforgeCoreModelTile *lowerRightOther);

FOUNDATION_EXPORT jint OrgMapsforgeCoreModelTile_getMaxTileNumberWithByte_(jbyte zoomLevel);

FOUNDATION_EXPORT void OrgMapsforgeCoreModelTile_initWithInt_withInt_withByte_withInt_(OrgMapsforgeCoreModelTile *self, jint tileX, jint tileY, jbyte zoomLevel, jint tileSize);

FOUNDATION_EXPORT OrgMapsforgeCoreModelTile *new_OrgMapsforgeCoreModelTile_initWithInt_withInt_withByte_withInt_(jint tileX, jint tileY, jbyte zoomLevel, jint tileSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreModelTile *create_OrgMapsforgeCoreModelTile_initWithInt_withInt_withByte_withInt_(jint tileX, jint tileY, jbyte zoomLevel, jint tileSize);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreModelTile)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreModelTile")
