//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/TileBitmap.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsTileBitmap")
#ifdef RESTRICT_OrgMapsforgeCoreGraphicsTileBitmap
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsTileBitmap 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreGraphicsTileBitmap 1
#endif
#undef RESTRICT_OrgMapsforgeCoreGraphicsTileBitmap

#if !defined (OrgMapsforgeCoreGraphicsTileBitmap_) && (INCLUDE_ALL_OrgMapsforgeCoreGraphicsTileBitmap || defined(INCLUDE_OrgMapsforgeCoreGraphicsTileBitmap))
#define OrgMapsforgeCoreGraphicsTileBitmap_

#define RESTRICT_OrgMapsforgeCoreGraphicsBitmap 1
#define INCLUDE_OrgMapsforgeCoreGraphicsBitmap 1
#include "org/mapsforge/core/graphics/Bitmap.h"

@class JavaLangBoolean;
@class JavaLangLong;

@protocol OrgMapsforgeCoreGraphicsTileBitmap < OrgMapsforgeCoreGraphicsBitmap, JavaObject >

- (jlong)getTimestamp;

- (bool)isExpired;

- (void)setExpirationWithLong:(jlong)expiration;

- (void)setTimestampWithLong:(jlong)timestamp;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreGraphicsTileBitmap)

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreGraphicsTileBitmap)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreGraphicsTileBitmap")
