//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/mapelements/WayTextContainer.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMapsforgeCoreMapelementsWayTextContainer")
#ifdef RESTRICT_OrgMapsforgeCoreMapelementsWayTextContainer
#define INCLUDE_ALL_OrgMapsforgeCoreMapelementsWayTextContainer 0
#else
#define INCLUDE_ALL_OrgMapsforgeCoreMapelementsWayTextContainer 1
#endif
#undef RESTRICT_OrgMapsforgeCoreMapelementsWayTextContainer

#if !defined (OrgMapsforgeCoreMapelementsWayTextContainer_) && (INCLUDE_ALL_OrgMapsforgeCoreMapelementsWayTextContainer || defined(INCLUDE_OrgMapsforgeCoreMapelementsWayTextContainer))
#define OrgMapsforgeCoreMapelementsWayTextContainer_

#define RESTRICT_OrgMapsforgeCoreMapelementsMapElementContainer 1
#define INCLUDE_OrgMapsforgeCoreMapelementsMapElementContainer 1
#include "org/mapsforge/core/mapelements/MapElementContainer.h"

@class JavaLangDouble;
@class JavaLangInteger;
@class NSString;
@class OrgMapsforgeCoreGraphicsDisplay;
@class OrgMapsforgeCoreGraphicsTextOrientation;
@class OrgMapsforgeCoreModelLineString;
@class OrgMapsforgeCoreModelPoint;
@class OrgMapsforgeCoreModelRectangle;
@class OrgMapsforgeCoreModelRotation;
@protocol OrgMapsforgeCoreGraphicsCanvas;
@protocol OrgMapsforgeCoreGraphicsGraphicFactory;
@protocol OrgMapsforgeCoreGraphicsMatrix;
@protocol OrgMapsforgeCoreGraphicsPaint;

@interface OrgMapsforgeCoreMapelementsWayTextContainer : OrgMapsforgeCoreMapelementsMapElementContainer {
 @public
  OrgMapsforgeCoreModelRectangle *boundary_;
}

#pragma mark Public

- (instancetype)initWithOrgMapsforgeCoreGraphicsGraphicFactory:(id<OrgMapsforgeCoreGraphicsGraphicFactory>)graphicFactory
                           withOrgMapsforgeCoreModelLineString:(OrgMapsforgeCoreModelLineString *)lineString
                           withOrgMapsforgeCoreGraphicsDisplay:(OrgMapsforgeCoreGraphicsDisplay *)display
                                                       withInt:(jint)priority
                                                  withNSString:(NSString *)text
                             withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paintFront
                             withOrgMapsforgeCoreGraphicsPaint:(id<OrgMapsforgeCoreGraphicsPaint>)paintBack
                                                    withDouble:(jdouble)textHeight
                   withOrgMapsforgeCoreGraphicsTextOrientation:(OrgMapsforgeCoreGraphicsTextOrientation *)textOrientation;

- (void)drawWithOrgMapsforgeCoreGraphicsCanvas:(id<OrgMapsforgeCoreGraphicsCanvas>)canvas
                withOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)origin
            withOrgMapsforgeCoreGraphicsMatrix:(id<OrgMapsforgeCoreGraphicsMatrix>)matrix
             withOrgMapsforgeCoreModelRotation:(OrgMapsforgeCoreModelRotation *)rotation;

- (NSString *)description;

#pragma mark Protected

- (OrgMapsforgeCoreModelRectangle *)getBoundary;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithOrgMapsforgeCoreModelPoint:(OrgMapsforgeCoreModelPoint *)arg0
               withOrgMapsforgeCoreGraphicsDisplay:(OrgMapsforgeCoreGraphicsDisplay *)arg1
                                           withInt:(jint)arg2 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMapsforgeCoreMapelementsWayTextContainer)

J2OBJC_FIELD_SETTER(OrgMapsforgeCoreMapelementsWayTextContainer, boundary_, OrgMapsforgeCoreModelRectangle *)

FOUNDATION_EXPORT void OrgMapsforgeCoreMapelementsWayTextContainer_initWithOrgMapsforgeCoreGraphicsGraphicFactory_withOrgMapsforgeCoreModelLineString_withOrgMapsforgeCoreGraphicsDisplay_withInt_withNSString_withOrgMapsforgeCoreGraphicsPaint_withOrgMapsforgeCoreGraphicsPaint_withDouble_withOrgMapsforgeCoreGraphicsTextOrientation_(OrgMapsforgeCoreMapelementsWayTextContainer *self, id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory, OrgMapsforgeCoreModelLineString *lineString, OrgMapsforgeCoreGraphicsDisplay *display, jint priority, NSString *text, id<OrgMapsforgeCoreGraphicsPaint> paintFront, id<OrgMapsforgeCoreGraphicsPaint> paintBack, jdouble textHeight, OrgMapsforgeCoreGraphicsTextOrientation *textOrientation);

FOUNDATION_EXPORT OrgMapsforgeCoreMapelementsWayTextContainer *new_OrgMapsforgeCoreMapelementsWayTextContainer_initWithOrgMapsforgeCoreGraphicsGraphicFactory_withOrgMapsforgeCoreModelLineString_withOrgMapsforgeCoreGraphicsDisplay_withInt_withNSString_withOrgMapsforgeCoreGraphicsPaint_withOrgMapsforgeCoreGraphicsPaint_withDouble_withOrgMapsforgeCoreGraphicsTextOrientation_(id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory, OrgMapsforgeCoreModelLineString *lineString, OrgMapsforgeCoreGraphicsDisplay *display, jint priority, NSString *text, id<OrgMapsforgeCoreGraphicsPaint> paintFront, id<OrgMapsforgeCoreGraphicsPaint> paintBack, jdouble textHeight, OrgMapsforgeCoreGraphicsTextOrientation *textOrientation) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMapsforgeCoreMapelementsWayTextContainer *create_OrgMapsforgeCoreMapelementsWayTextContainer_initWithOrgMapsforgeCoreGraphicsGraphicFactory_withOrgMapsforgeCoreModelLineString_withOrgMapsforgeCoreGraphicsDisplay_withInt_withNSString_withOrgMapsforgeCoreGraphicsPaint_withOrgMapsforgeCoreGraphicsPaint_withDouble_withOrgMapsforgeCoreGraphicsTextOrientation_(id<OrgMapsforgeCoreGraphicsGraphicFactory> graphicFactory, OrgMapsforgeCoreModelLineString *lineString, OrgMapsforgeCoreGraphicsDisplay *display, jint priority, NSString *text, id<OrgMapsforgeCoreGraphicsPaint> paintFront, id<OrgMapsforgeCoreGraphicsPaint> paintBack, jdouble textHeight, OrgMapsforgeCoreGraphicsTextOrientation *textOrientation);

J2OBJC_TYPE_LITERAL_HEADER(OrgMapsforgeCoreMapelementsWayTextContainer)


#endif

#pragma pop_macro("INCLUDE_ALL_OrgMapsforgeCoreMapelementsWayTextContainer")
